Description of fitsfindkey_strmhead
fitsfindkey_strmhead
PURPOSE
fitsfindkey_strmhead - Searches a FITS header H for keyword S
SYNOPSIS
function [j_out] = fitsfindkey_strmhead(H,S)
DESCRIPTION
 fitsfindkey_strmhead - Searches a FITS header H for keyword S
 Calling:
  [J] = fitsfindkey_strmhead(H,S)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
gtopo2maps GTOPO2MAPS - Parse gtopo digital elevation models
KoschSBIG_HAARP KoschSBIG_HAARP parses an fits header for observation info
KoschSBIG_HIPAS2007 LANCS_APOGEE_FITS parses an fits header for observation info
lancs_apogee_fits LANCS_APOGEE_FITS parses an fits header for observation info
fits_header2infostruct FITS_HEADER2INFOSTRUCT - parse fits header, make struct of meta-data
try_to_be_smart TRY_TO_BE_SMART parses an (ALIS) fits header for observation info
SOURCE CODE
function [j_out] = fitsfindkey_strmhead(H,S)
% fitsfindkey_strmhead - Searches a FITS header H for keyword S
%
% Calling:
%  [J] = fitsfindkey_strmhead(H,S)
% Copyright Peter Rydesaeter
j_out=[];%if not found return empty
ji = 1;
for i1 = 1:size(H,1)
  if findstr(lower(H(i1,1:12)), lower(S)),
    j_out(ji) = i1;
    ji = ji+1;
  end
end