Description of ASK_v_select
ASK_v_select
PURPOSE
ASK_V_SELECT - Set current camera index in global structure VS
SYNOPSIS
function ASK_v_select(indx,quiet)
DESCRIPTION
 ASK_V_SELECT - Set current camera index in global structure VS
 Calling:
   ASK_v_select(indx)
CROSS-REFERENCE INFORMATION
This function calls:
ASK_get_imcal ASK_GET_IMCAL - routine filling the imcal common block with
ASK_v_summary ASK_V_SUMMARY - print summary of event setup
This function is called by:
ASK_add_int_radar ASK_ADD_INT_RADAR - Image intenisity inside radar beam.
ASK_fanograms ASK_FANOGRAMS - Produce keograms of a fan-beam-cut from an ASK image sequence
ASK_image_sequence ASK_IMAGE_SEQUENCE - to display an ASK image sequence as movie, and
ASK_keogram_overlayed ASK_KEOGRAM_OVERLAYED - to plot an overlayed keogram, ASK images, and
ASK_keograms ASK_KEOGRAMS - Produce keograms keograms from an ASK image sequence
SOURCE CODE
function ASK_v_select(indx,quiet)
% ASK_V_SELECT - Set current camera index in global structure VS
%
% Calling:
%   ASK_v_select(indx)
% Modified from add_multi.pro
% Copyright Bjorn Gustavsson 20110131
% GPL 3.0 or later applies
global vs
max_camera_number = length(vs.vnf);
% Constrain indx to be between 1 and the maximum camera number:
indx = max(1,min(max_camera_number,indx));
vs.vsel = indx;
ASK_get_imcal
if nargin == 1 | (quiet == 0 & ~strcmp(quiet,'quiet'))
  ASK_v_summary
end