Description of ASK_time2indx
ASK_time2indx
PURPOSE
ASK_TIME2INDX - returns the imasge index for a time-vector
SYNOPSIS
function i1 = ASK_time2indx(timevec)
DESCRIPTION
 ASK_TIME2INDX - returns the imasge index for a time-vector
 Calling:
   indx = ASK_time2indx([yyyy, mm, dd, hh, mm, ss])
CROSS-REFERENCE INFORMATION
This function calls:
ASK_dat2str DAT2STR - convert a modified Julian second (mjs) to date string
ASK_time2MJS ASK_time2MJS - converts calendar date to modified Julian second
ASK_time_v ASK_TIME_V - returns time since the start of the sequence
This function is called by:
SOURCE CODE
function i1 = ASK_time2indx(timevec)
% ASK_TIME2INDX - returns the imasge index for a time-vector
%
% Calling:
%   indx = ASK_time2indx([yyyy, mm, dd, hh, mm, ss])
global vs
TT_MJS = ASK_time2MJS(timevec);
Tstart = ASK_time_v(1,1);
Tend = ASK_time_v(vs.vnl(vs.vsel),1);
if Tstart <= TT_MJS & TT_MJS <= Tend
  i1 = 1;
  while i1 <= vs.vnl(vs.vsel) & ASK_time_v(i1+1,1) < TT_MJS
    i1 = i1 + 1;
  end
else
  i1 = [];
  disp(['Warning. time: ',datestr(timevec,'yyyy/mm/dd HH:MM:SS.FFF'),' is not found between: ',ASK_dat2str(ASK_time_v(1,1)),' and: ',ASK_dat2str(ASK_time_v(vs.vnl(vs.vsel),1))])
end