Description of ASK_dat2str
ASK_dat2str
PURPOSE
DAT2STR - convert a modified Julian second (mjs) to date string
SYNOPSIS
function str = ASK_dat2str(MJS,FormatNrOrStr)
DESCRIPTION
 DAT2STR - convert a modified Julian second (mjs) to date string
 Calling:
   str = dat2str(MJS,FormatNrOrStr)
 Input:
   MJS - array with times in modified Julian seconds (since 1950/1/1-00:00)
   FormatNrOrStr - format identifier/number or free format string,
                   see DATESTR for details. (optional, if left out
                   format yyyy/mm/dd-HH:MM:SS.FFF will be used, 31
                   is a good option, 30 is ISO 8601)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ASK_image_sequence IMAGE_SWQUENCE - to display an ASK image sequence as movie, and
ASK_indx2datevec ASK_INDX2DATEVEC - Convert a frame index into a [yyyy,mm,dd,HH,MM,SS.FFF]
ASK_print_dat ASK_PRINT_DAT - prints the date corresponding to a modified
ASK_read_vs ASK_READ_VS - the procedure to read the videoevent setup - the new version
ASK_time2indx ASK_TIME2INDX - returns the imasge index for a time-vector
ASK_v_summary ASK_V_SUMMARY - print summary of event setup
SOURCE CODE
function str = ASK_dat2str(MJS,FormatNrOrStr)
% DAT2STR - convert a modified Julian second (mjs) to date string
%
% Calling:
%   str = dat2str(MJS,FormatNrOrStr)
% Input:
%   MJS - array with times in modified Julian seconds (since 1950/1/1-00:00)
%   FormatNrOrStr - format identifier/number or free format string,
%                   see DATESTR for details. (optional, if left out
%                   format yyyy/mm/dd-HH:MM:SS.FFF will be used, 31
%                   is a good option, 30 is ISO 8601)
% Modified from dat2str.pro
% Copyright Bjorn Gustavsson 20110128
% GPL 3.0 or later applies
if nargin == 1
 FormatNrOrStr = 'yyyy/mm/dd-HH:MM:SS.FFF';
end
% let Matlab date-functions do the job:
str = datestr(MJS/(24*3600)+datenum([1950,1,1]),FormatNrOrStr);