Description of ASK_bias
ASK_bias
PURPOSE
ASK_BIAS - returns the bias drift of of megablock, by measuring the
SYNOPSIS
function delta = ASK_bias(file)
DESCRIPTION
 ASK_BIAS - returns the bias drift of of megablock, by measuring the
 difference between the average of the darks after the megablock
 and the darks before the megablock.
 Calling:
  delta = ASK_bias(file)
 Input:
  file - directory name of megablock of interest, for example
         '20061022204134r1'
 Output:
  delta - difference, bias_after - bias_before
 Written to mimmick bias.pro made by Hanna Dahlgren on 3 Feb 2011.
CROSS-REFERENCE INFORMATION
This function calls:
ASK_get_dark_name ASK_GET_DARK_NAME - get the name of the dark megablock corresponding to the
ASK_read_v ASK_READ_V -
ASK_read_vs ASK_READ_VS - the procedure to read the videoevent setup - the new version
This function is called by:
SOURCE CODE
function delta = ASK_bias(file)
% ASK_BIAS - returns the bias drift of of megablock, by measuring the
% difference between the average of the darks after the megablock
% and the darks before the megablock.
%
% Calling:
%  delta = ASK_bias(file)
% Input:
%  file - directory name of megablock of interest, for example
%         '20061022204134r1'
% Output:
%  delta - difference, bias_after - bias_before
%
% Written to mimmick bias.pro made by Hanna Dahlgren on 3 Feb 2011.
global hities
global vs
dir = videodir; % TODO - find out from where to get this!
[dark1_path,dark1_name] = ASK_get_dark_name(dpath);
[dark2_path,dark2_name] = ASK_get_dark_name(dpath,'later');
ASK_read_vs([dark1_name,'.txt'],'quiet')
dark1 = zeros(256,256,640);
dd1 = zeros(640,1);
dd2 = zeros(640,1);
for i1 = 1:640,
  im = ASK_read_v(i1);
  dark1(*,*,i1-1) = im;
  dd1(i1-1) = mean(im(:));
end
ASK_read_vs([dark2_name,'.txt'],'quiet')
dark2 = zeros(256,256,640)
for i1 = 1:640,
  im = ASK_read_v(i1);
  dark2(i1-1,*,*) = im;
  dd2(i1-1) = mean(im(:));
end
% Discard the highest and lowest values
sorted_dark1 = sort(dd1);
sorted_dark2 = sort(dd2);
mean1 = mean(dd1(sorted_dark1(5:635)));
mean2 = mean(dd2(sorted_dark2(5:635)));
delta = mean2 - mean1;
% $$$ ;Function that returns the bias drift of the megablock, by measuring the difference between the average of the darks after the megablock and the darks before the megablock. Made by HD on 3 Feb 2011.
% $$$ ;
% $$$ ;
% $$$ ;Input:  file  The name of the megablock of interest, for example '20061022204134r1'
% $$$
% $$$
% $$$ ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
% $$$ common hities
% $$$ common vs
% $$$
% $$$
% $$$ dir=videodir
% $$$
% $$$ get_dark_name,dir+file+'/',dark1_path,dark1_name
% $$$ get_dark_name,dir+file+'/',dark2_path,dark2_name,/later
% $$$
% $$$
% $$$ read_vs,file=dark1_name+'.txt',/quiet
% $$$
% $$$ dark1=fltarr(640,256,256)
% $$$
% $$$ dd1=fltarr(640)
% $$$ dd2=fltarr(640)
% $$$
% $$$ for i=1,640 do begin
% $$$
% $$$ read_v,i,im
% $$$
% $$$ dark1(i-1,*,*)=im
% $$$ dd1(i-1)=mean(im)
% $$$ endfor
% $$$
% $$$ read_vs,file=dark2_name+'.txt',/quiet
% $$$ dark2=fltarr(640,256,256)
% $$$
% $$$ for i=1,640 do begin
% $$$
% $$$ read_v,i,im
% $$$ dark2(i-1,*,*)=im
% $$$ dd2(i-1)=mean(im)
% $$$ endfor
% $$$
% $$$ ;;Discard the highest and lowest values
% $$$
% $$$ sorted_dark1=sort(dd1)
% $$$ sorted_dark2=sort(dd2)
% $$$
% $$$
% $$$ mean1=mean(dd1(sorted_dark1(5:635)))
% $$$ mean2=mean(dd2(sorted_dark2(5:635)))
% $$$
% $$$ delta=mean2-mean1
% $$$
% $$$ return,delta
% $$$
% $$$
% $$$ end