function SkMp = errorgui(SkMp)
% ERRORGUI - Create the figure and GUI for the errorplots
%
% Calling:
% SkMp = errorgui(SkMp)

%   Copyright ©  2001 by Bjorn Gustavsson <bjorn.gustavsson@irf.se>
%   This is free software, licensed under GNU GPL version 2 or later

errorload = '[SkMp] = loaderrordata(SkMp);';
errorsave = '[SkMp] = saveerrordata(SkMp);';
SkMp.errorfig = figure;
 
figure(SkMp.figsky)

SkMp.uic3(6,1) = uimenu('Label','Errorplots');
SkMp.uic3(6,13) = uimenu(SkMp.uic3(6,1), ...
			'Label','Load saved error data', ...
			'callback', ...
			errorload);
SkMp.uic3(6,14) = uimenu(SkMp.uic3(6,1), ...
			'Label','Save error data', ...
			'callback', ...
			errorsave);
SkMp.uic3(6,2) = uimenu(SkMp.uic3(6,1), ...
			'Label','Error arrows', ...
			'callback', ...
			'starerrorplot(SkMp,1)');
SkMp.uic3(6,3) = uimenu(SkMp.uic3(6,1), ...
			'Label','Error scatter', ...
			'callback', ...
			'starerrorplot(SkMp,2)');
SkMp.uic3(6,4) = uimenu(SkMp.uic3(6,1), ...
			'Label','du of u', ...
			'callback', ...
			'starerrorplot(SkMp,3)');
SkMp.uic3(6,5) = uimenu(SkMp.uic3(6,1), ... 
			'Label','dv of v', ...
			'callback', ...
			'starerrorplot(SkMp,4)');
SkMp.uic3(6,6) = uimenu(SkMp.uic3(6,1), ...
			'Label','dr of r', ...
			'callback', ...
			'starerrorplot(SkMp,5)');
SkMp.uic3(6,7) = uimenu(SkMp.uic3(6,1), ...
			'Label','dphi of phi', ...
			'callback', ...
			'starerrorplot(SkMp,6)');
SkMp.uic3(6,12) = uimenu(SkMp.uic3(6,1), ...
			 'Label','dphi of r', ...
			 'callback', ...
			 'starerrorplot(SkMp,11)');
SkMp.uic3(6,8) = uimenu(SkMp.uic3(6,1), ...
			'Label','hist(du)', ...
			'callback', ...
			'starerrorplot(SkMp,7)');
SkMp.uic3(6,9) = uimenu(SkMp.uic3(6,1), ...
			'Label','hist(dv)', ...
			'callback', ...
			'starerrorplot(SkMp,8)');
SkMp.uic3(6,10) = uimenu(SkMp.uic3(6,1), ...
			 'Label','hist(dr)', ...
			 'callback', ...
			 'starerrorplot(SkMp,9)');
SkMp.uic3(6,11) = uimenu(SkMp.uic3(6,1), ...
			 'Label','hist(dphi)', ...
			 'callback', ...
			 'starerrorplot(SkMp,10)');

% $$$ hidegui(SkMp.uic3(6,:),'callback')
set(SkMp.uic3(6,:),'handlevisibility','callback')
