Description of spc_save_bad_intens
spc_save_bad_intens
PURPOSE
SPC_SAVE_BAD_INTENS - saves bad times for spectral calibration
SYNOPSIS
function err = spc_save_bad_intens(gI1,gI2,gI3,gT,gX,gY,gfilter, filename)
DESCRIPTION
 SPC_SAVE_BAD_INTENS - saves bad times for spectral calibration
CROSS-REFERENCE INFORMATION
This function calls:
backup1000filesversions BACKUP1000FILESVERSIONS - Backup files to prevent overwriting them
This function is called by:
Spec_cal_jobb_Miracle Spec_cal_jobb_Miracle - Example of spectral camera sensitivity calibration
Spec_cal_jobb_exmplCell Spec_cal_jobb_exmplCell - Example of spectral camera sensitivity calibration
SOURCE CODE
function err = spc_save_bad_intens(gI1,gI2,gI3,gT,gX,gY,gfilter, filename)
% SPC_SAVE_BAD_INTENS - saves bad times for spectral calibration
%
% Copyright M V
% path = '.data/spc/';
path = './';
err = 0;
status = -12;
message = '';
disp(sprintf('\nWriting data to file %s...\n', filename))
try
  if exist(fullfile(path,filename),'file')
    [status, message] = backup1000filesversions(fullfile(path,filename));
  end
  save(fullfile(path,filename), 'gI1', 'gI2', 'gI3', 'gT', 'gX', 'gY', 'gfilter');
  disp(sprintf('OK.'))
catch
  disp(sprintf('\nWriting %s failed:\n%d:%s\n', [path filename], status, message))
  err = 1;
end