Description of ASK_TT_MJS
ASK_TT_MJS
PURPOSE
ASK_TT_MJS - converts calendar date to modified Julian second
SYNOPSIS
function TT_MJS = ASK_TT_MJS(date_vec)
DESCRIPTION
 ASK_TT_MJS - converts calendar date to modified Julian second
   (seconds elapsed since 00:00 UT on Jan 1, 1950)
 Calling:
   TT_MJS = ASK_TT_MJS(date_vec)
 Input:
   date_vec - array with rows of: [yyyy,mm,dd,(hh,mm,ss.ms)]
 Output:
   TT_MJS - seconds since 00:00 UT on Jan 1, 1950
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ASK_enable_datadir ASK_ENABLE_DATADIR - short routine to automatically enable
ASK_get_dark_name ASK_GET_DARK_NAME - get the name of the dark megablock corresponding to the
ASK_mjs_dy ASK_MJS_DY - convert mjs time to decimal years
ASK_read_asklut ASK_READ_ASKLUT - reads ASK meta-datafrom look up tables
ASK_read_cnvlut ASK_READ_CNVLUT - reads the camera parameter lookup table
ASK_read_sst ASK_READ_SST - A procedure to read the start and stop times from a string
ASK_read_vs ASK_READ_VS - the procedure to read the videoevent setup - the new version
ASK_time_axis ASK_TIME_AXIS - formated time onto the x-labels
ASK_time_tick ASK_TIME_AXIS - suitable settings for time tick marks and labels.
SOURCE CODE
function TT_MJS = ASK_TT_MJS(date_vec)
% ASK_TT_MJS - converts calendar date to modified Julian second
%   (seconds elapsed since 00:00 UT on Jan 1, 1950)
%
% Calling:
%   TT_MJS = ASK_TT_MJS(date_vec)
% Input:
%   date_vec - array with rows of: [yyyy,mm,dd,(hh,mm,ss.ms)]
% Output:
%   TT_MJS - seconds since 00:00 UT on Jan 1, 1950
% Modified from TT_MJS.pro
% Copyright Bjorn Gustavsson 20110128
% GPL 3.0 or later applies
% Let mathworks date-functions do the heavy lifting:
TT_MJS = (double(datenum(date_vec)) - double(datenum([1950,1,1])))*24*3600;