Description of runner4FlamingRays
runner4FlamingRays
PURPOSE
runner4FlamingRays - Estimate electron precipitation variation with E and Y
SYNOPSIS
function Ibest = runner4FlamingRays(indices2run,Keos,IstartGuesses,Ibestest,trmtr2Dto1D,A1Z,A2Z,E,Y,Z,OPS)
DESCRIPTION
 runner4FlamingRays - Estimate electron precipitation variation with E and Y
 from multimonochromatic narrow-field-of-view imaging.
 Calling
   Ibest = runner4FlamingRays(indices2run,Keos,IstartGuesses,Ibestest,trmtr2Dto1D,A1Z,A2Z,E,Y,Z,OPS)
 Input:
  indices2run   - Array with indices of time-steps for keograms to
                  run the fitting procedure on.
  Keos          - Cell array with keograms { 1 x 3 } with keograms
                  {[nT x nPix],[],[nT x nPix]}
                  from fanbeam made from pixels with
                  lines-of-sight in plane || B
  IstartGuesses - Start guesses for electron spectra producing the
                  emissions.
  trmtr2Dto1D   - Projection matrix from volume emission rates in
                  plane (Y,Z) to pixel coordinates in keogram
  A1Z           - Electron Energy flux to volume emission altitude
                  profile matrix mapping Ie(E) to I_lambda(z) for
                  emission 1 [nZ x nE]
  A2Z           - same as above for emission #3
  E             - Electron energy array [1 x nE] (keV)
  Y             - 2-D array of horizontal spatial position of
                  volume elements [nZ x nY] (km)
  Z             - 2-D array of vertical spatial position of
                  volume elements [nZ x nY] (km)
  OPS           - Options structure
CROSS-REFERENCE INFORMATION
This function calls:
err4FlamingRays 1 2 3 4 5 6 7 8 9 0 11 12
err4FlamingRaysC err4FlamingRaysC - error function for estimating electron spectra
imgs_smart_caxis imgs_smart_caxis - alpha-percentile setting of color-axis,
errDeParallax2DiffuseS errDeParallax2DiffuseS - error function for estimating electron spectra
fminsearchbnd FMINSEARCHBND: FMINSEARCH, but with bound constraints by transformation
inpaint_nans INPAINT_NANS: in-paints over nans in an array
medfilt2 MEDFILT2 - 2 dimensional sliding median filter
merge_structs MERGE_STRUCTS - Merge all fields of S2 into S1.
This function is called by:
SOURCE CODE
function Ibest = runner4FlamingRays(indices2run,Keos,IstartGuesses,Ibestest,trmtr2Dto1D,A1Z,A2Z,E,Y,Z,OPS)
% runner4FlamingRays - Estimate electron precipitation variation with E and Y
% from multimonochromatic narrow-field-of-view imaging.
%
% Calling
%   Ibest = runner4FlamingRays(indices2run,Keos,IstartGuesses,Ibestest,trmtr2Dto1D,A1Z,A2Z,E,Y,Z,OPS)
% Input:
%  indices2run   - Array with indices of time-steps for keograms to
%                  run the fitting procedure on.
%  Keos          - Cell array with keograms { 1 x 3 } with keograms
%                  {[nT x nPix],[],[nT x nPix]}
%                  from fanbeam made from pixels with
%                  lines-of-sight in plane || B
%  IstartGuesses - Start guesses for electron spectra producing the
%                  emissions.
%  trmtr2Dto1D   - Projection matrix from volume emission rates in
%                  plane (Y,Z) to pixel coordinates in keogram
%  A1Z           - Electron Energy flux to volume emission altitude
%                  profile matrix mapping Ie(E) to I_lambda(z) for
%                  emission 1 [nZ x nE]
%  A2Z           - same as above for emission #3
%  E             - Electron energy array [1 x nE] (keV)
%  Y             - 2-D array of horizontal spatial position of
%                  volume elements [nZ x nY] (km)
%  Z             - 2-D array of vertical spatial position of
%                  volume elements [nZ x nY] (km)
%  OPS           - Options structure
% 4 options:
dOPS.Plot4ShowInRun = 0;
dOPS.verNR = 5;
dOPS.saveFileBaseName = 'arc_split_fitS-200612150217-600to700';%-%02d-%02d.mat'
dOPS.forReals = 0;
if nargin == 0
  Ibest = dOPS;
  return
end
if nargin > 8
  dOPS = merge_structs(dOPS,OPS);
end
if ~isfield(dOPS,'z_max') | isempty(dOPS.z_max)
  z_max = 106;
else
  z_max = dOPS.z_max;
end
for i1 = 1:size(ImStack{1},3),
  img4bg = wiener2(medfilt2(ImStack{1}(:,:,i1),[3,3]),[3,3]);
  img4bg(bgMask==1) = nan;
  imbg{1}(:,:,i1) = inpaint_nans(img4bg,4);
  img4bg = wiener2(medfilt2(ImStack{3}(:,:,i1),[3,3]),[3,3]);
  img4bg(bgMask==1) = nan;
  imbg{3}(:,:,i1) = inpaint_nans(img4bg,4);
end
for i1 = 1:size(ImStack{1},3),
  imagesc(imbg{1}(:,:,i1)),cX = imgs_smart_caxis(0.003,imbg{1}(:,:,i1));colorbar
  caxis([-0.2 1]*cX(2))
  pause
end
for i1 = 1:size(ImStack{1},3),
  Iq = wiener2(ImStack{3}(150:240,160:256,i1),[3,3])-imbg{3}(150:240,160:256,i1)*1;
  imagesc(Iq),cX = imgs_smart_caxis(0.003,Iq);colorbar
  caxis([-0.2 1]*cX(2))
  pause
end
for i1 = 1:size(ImStack{1},3),
  Iq = wiener2(ImStack{1}(150:240,160:256,i1),[3,3])-imbg{1}(150:240,160:256,i1)*1;
  imagesc(Iq),cX = imgs_smart_caxis(0.003,Iq);colorbar
  caxis([-0.2 1]*cX(2))
  pause
end
fmsOPS = optimset('fminsearch');
fmsOPS.Display = 'iter';
%            I0        x0     dx           y0      dy       g_x     E0      dE      g_E     g_E2     I1      E0      dE        g_E     g_E2
parTest = [ 4.7336,   -6.0518, 0.0021721, -12.553, 0.39745, 2.2325, 3.2487, 2.9215, 2.9828, 0.47734,  0.927, 16.56,  0.044845, 1.8183, 1];
parMin = [  eps(1),-12.0518, ds*1/3,    -18.553, ds*1/3,  0.6325, 0.3248, 0.9215, 0.5828, 0.25,      eps(1),  0.56,  0.044845, 0.5183, 0.25];
parMax = [473.36,     -0.0518, 2.1721,     -6.553, 3.9745,  4.2325,32.487, 29.215,  4.9828, 2.47734, 21.927, 16.56, 12.044845, 3.8183, 3.7833];
v_p =    [  1          2       3            4      5        6       7       8       9      10        11      17     18        19      20];
vpI = [1 11];
parI = parTest([1 11]);
parI = fminsearchbnd(@(I) err4FlamingRays(I,vpI,I0b,stns,{bgMask,bgMask},ZfI,XfI(:,:,115),YfI(:,:,115),{A2Z,A1Z},E,1,110),parI,[eps(1) eps(1)],[1e6 1e6],fmsOPS);
parTest([1 11]) = parI;
errMask = bgMask;
errMask(:,250:end) = 0;
for i1 = 1:size(ImStack{1},3),
  Iq = ( wiener2(ImStack{1}(:,:,i1),[3,3]) - wiener2(imbg{1}(:,:,i1),[3,3]) ) * 1/C_filter6370;
  stns(1).img = Iq;
  Iq = ( wiener2(ImStack{3}(:,:,i1),[3,3]) - wiener2(imbg{3}(:,:,i1),[3,3]) ) * 1/C_filter7774;
  stns(2).img = Iq;
  %parTest = fminsearch(@(I) err4FlamingRays(I,v_p,I0b,stns,{bgMask,bgMask},ZfI,XfI(:,:,115),YfI(:,:,115),{A2Z,A1Z},E,1,110),parTest);
  parTest = fminsearchbnd(@(I) err4FlamingRays(I,v_p,I0b,stns,{errMask,errMask},ZfI,XfI(:,:,115),YfI(:,:,115),{A2Z,A1Z},E,1,110),parTest,parMin,parMax,fmsOPS);
  It(i1,:) = parTest;
end
ItC = It(:,[1,2,4,3,6:end])/2 + It(:,[1,2,4,5,6:end])/2;
%            I0     x0        y0      dS         g_x     E0      dE      g_E     g_E2     I1      E0    dE         g_E     g_E2
parIC = [ 4.7336,   -6.0518, -12.553, 0.0021721, 2.2325, 3.2487, 2.9215, 2.9828, 0.47734, 0.927, 16.56,  0.044845, 1.8183, 1];
pICMin = [  eps(1),-12.0518, -18.553, ds*1/3,    0.6325, 0.3248, 0.9215, 0.5828, 0.25,   eps(1),  0.56,  0.044845, 0.5183, 0.25];
pICMax = [473.36,   -0.0518,  -6.553, 2.1721,    4.2325,32.487, 29.215,  4.9828, 2.47734,21.927, 16.56, 12.044845, 3.8183, 3.7833];
vpC =    [  1          2       3          4      5       6       7       8       9       10      15     16         17      18];
fmsOPS.Display = 'final';
for i1 = 1:size(ImStack{1},3),
  Iq = ( wiener2(ImStack{1}(:,:,i1),[3,3]) - wiener2(imbg{1}(:,:,i1),[3,3]) ) * 1/C_filter6370;
  stns(1).img = Iq;
  Iq = ( wiener2(ImStack{3}(:,:,i1),[3,3]) - wiener2(imbg{3}(:,:,i1),[3,3]) ) * 1/C_filter7774;
  stns(2).img = Iq;
  parTest = fminsearchbnd(@(I) err4FlamingRaysC(I,vpC,I0C,stns,{errMask,errMask},ZfI,XfI(:,:,115),YfI(:,:,115),{A2Z,A1Z},E,1,110),ItC(i1,:),pICMin,pICMax,fmsOPS);
  ItC(i1,:) = parTest;
end
fmsOPS.Display = 'final';
for i1 = 1:size(ImStack{1},3),
  Iq = ( wiener2(ImStack{1}(:,:,i1),[3,3]) - wiener2(imbg{1}(:,:,i1),[3,3]) ) * 1/C_filter6370;
  stns(1).img = Iq;
  Iq = ( wiener2(ImStack{3}(:,:,i1),[3,3]) - wiener2(imbg{3}(:,:,i1),[3,3]) ) * 1/C_filter7774;
  stns(2).img = Iq;
  pICMin(2:3) = ItC0(i1,2:3)-0.5;
  pICMax(2:3) = ItC0(i1,2:3)+0.5;
  parTest = fminsearchbnd(@(I) err4FlamingRaysC(I,vpC,I0C,stns,{errMask,errMask},ZfI,XfI(:,:,115),YfI(:,:,115),{A2Z,A1Z},E,1,110),ItC0(i1,:),pICMin,pICMax,fmsOPS);
  ItC(i1,:) = parTest;
end
for i1 = 1:size(ImStack{1},3),
  Iq = ( wiener2(ImStack{1}(:,:,i1),[3,3]) - wiener2(imbg{1}(:,:,i1),[3,3]) ) * 1/C_filter6370;
  stns(1).img = Iq;
  Iq = ( wiener2(ImStack{3}(:,:,i1),[3,3]) - wiener2(imbg{3}(:,:,i1),[3,3]) ) * 1/C_filter7774;
  stns(2).img = Iq;
  %parTest = fminsearch(@(I) err4FlamingRays(I,v_p,I0b,stns,{bgMask,bgMask},ZfI,XfI(:,:,115),YfI(:,:,115),{A2Z,A1Z},E,1,110),parTest);
  parTest = fminsearchbnd(@(I) err4FlamingRays(I,vpC,I0C,stns,{errMask,errMask},ZfI,XfI(:,:,115),YfI(:,:,115),{A2Z,A1Z},E,1,110),ItC(i1,:),pICMin,pICMax,fmsOPS);
  It2(i1,:) = parTest;
end
subplot(3,1,1)
pcolor([1:20]*1/32,E*1e3,log10(IeRay')),shading flat,caxis([-5 0]+max(caxis))
set(gca,'yscale','log')
hold on
for i1 = 1:size(ImStack{1},3),
  Iq = ( wiener2(ImStack{1}(:,:,i1),[3,3]) - wiener2(imbg{1}(:,:,i1),[3,3]) ) * 1/C_filter6370;
  stns(1).img = Iq;
  Iq = ( wiener2(ImStack{3}(:,:,i1),[3,3]) - wiener2(imbg{3}(:,:,i1),[3,3]) ) * 1/C_filter7774;
  stns(2).img = Iq;
  res = err4FlamingRaysC(ItC(i1,:),vpC,I0C,stns,{errMask,errMask},ZfI,XfI(:,:,115),YfI(:,:,115),{A2Z,A1Z},E,2,110);
  subplot(3,1,1)
  %semilogy(E,res.IeOutput{1})
  ph = plot((i1+0.5)/32*[1 1],E([1,end])*1e3,'k');
  subplot(3,2,3)
  imagesc(res.currImg{1}),imgs_smart_caxis(0.0003,res.currImg{1}),axis([150 256 150 256])
  subplot(3,2,4)
  imagesc(res.currImg{2}),imgs_smart_caxis(0.0003,res.currImg{2}),axis([150 256 150 256])
  subplot(3,2,5)
  imagesc(res.currProj{1}),imgs_smart_caxis(0.0003,res.currImg{1}),axis([150 256 150 256])
  subplot(3,2,6)
  imagesc(res.currProj{2}),imgs_smart_caxis(0.0003,res.currImg{2}),axis([150 256 150 256])
  mRay(i1) = getframe(gcf);
  delete(ph)
end
pT = [  4.804
      -6.0539
    0.0020815
       -13.27
      0.39244
       2.6325
       3.3457
       2.8948
        2.581
      0.44457
       16.479
       16.755
     0.050126
        2.333
       1.6808];
pT2 = [ 4.804
      -6.0539
    0.0020815
       -13.27
      0.39244
       2.6325
       3.3457
       2.8948
        2.581
      0.44457
       16.479
       1.5893
       16.752
     0.050126
        2.333
      -1.6808];
disp('Starts with the Fit-n-Run!')
fmsOPS = optimset('fminsearch');
fmsOPS.Display = 'iter';
for iT = indices2run,
  %errOps.saveruns = sprintf('errlog%s-%02d.dat',dOPS.saveFileBaseName,iT);
  [I0v,I0,v_p,bias_val,bias_Amp,Iupper,Ilower] = arc_split_reordernmerge_I0vpNbias(Ibestest{iT},IstartGuesses{iT},1);
  %whos I0v I0 v_p bias_val bias_Amp Iupper Ilower
  CurrCuts = {4*Keos{1}(:,iT),Keos{3}(:,iT)};
  %testE0 = errDeParallax2DiffuseS(I0v,v_p,I0,1e-12*trmtr2Dto1D,{4*A1Z,A2Z},E,CurrCuts,Y,Z,[],[],2);
  if dOPS.Plot4ShowInRun
    testRes = errDeParallax2DiffuseS(I0v,v_p,I0,1e-12*trmtr2Dto1D,{4*A1Z,A2Z},E,CurrCuts,Y,Z,[],[],2,z_max);
    arc_split_plotTestRes1(testRes,iT,1,[],[],[])
  end
  %keyboard
  disp(sprintf('%d %02d-%02d-%02d %02d:%02d:%05.2f',iT,clock))
  [Ip1F{iT},fv1(iT),exitflag,output] = fminsearchbnd(@(I) errDeParallax2DiffuseS(I,v_p,I0,1e-12*trmtr2Dto1D,{4*A1Z,A2Z},E,CurrCuts,Y,Z,bias_Amp',bias_val',1,z_max),I0v,Ilower,Iupper,fmsOPS);
  fmsOPS.Display = 'notify';
  if dOPS.forReals
    I0c = I0;
    I0c(v_p) = Ip1F{iT};
    I0c = I0c(v_p);
    I0c = Ip1F{iT}; % Has to be identical to the above!
    [Ip1{iT},fv2(iT),exitflag,output] = fminsearchbnd(@(I) errDeParallax2DiffuseS(I,v_p,I0,1e-12*trmtr2Dto1D,{4*A1Z,A2Z},E,CurrCuts,Y,Z,bias_Amp',bias_val',1,z_max),I0c,Ilower,Iupper,fmsOPS);
    I0c = I0;
    I0c(v_p) = Ip1{iT};
    I0c = I0c(v_p);
    I0c = Ip1{iT}; % Has to be identical to the above!
    [Ip1{iT},fv2(iT),exitflag,output] = fminsearchbnd(@(I) errDeParallax2DiffuseS(I,v_p,I0,1e-12*trmtr2Dto1D,{4*A1Z,A2Z},E,CurrCuts,Y,Z,bias_Amp',bias_val',1,z_max),I0c,Ilower,Iupper,fmsOPS);
    I0c = I0;
    I0c(v_p) = Ip1{iT};
    I0c = I0c(v_p);
    I0c = Ip1{iT}; % Has to be identical to the above!
    [Ip1{iT},fv2(iT),exitflag,output] = fminsearchbnd(@(I) errDeParallax2DiffuseS(I,v_p,I0,1e-12*trmtr2Dto1D,{4*A1Z,A2Z},E,CurrCuts,Y,Z,bias_Amp',bias_val',1,z_max),I0c,Ilower,Iupper,fmsOPS);
  end
  Ibest{iT} = Ip1{iT};
  testRes = errDeParallax2DiffuseS(Ip1{iT},v_p,I0,1e-12*trmtr2Dto1D,{4*A1Z,A2Z},E,CurrCuts,Y,Z,[],[],2,z_max);
  if dOPS.Plot4ShowInRun
    arc_split_plotTestRes1(testRes,iT,2,[],[],[])
    print('-depsc2','-painters',sprintf([dOPS.saveFileBaseName,'-%d-%03d'],dOPS.verNR,iT))
  end
  disp(sprintf('%d %02d-%02d-%02d %02d:%02d:%05.2f',iT,clock))
  testresfile = sprintf('%s-%02d-%02d.mat',dOPS.saveFileBaseName,dOPS.verNR,iT);
  save(testresfile,'testRes','Ibest')
end