function avok = avok_create(avok)
% AVOK_CREATE - create alis-view-overview-keograms user interface
%   
% Calling:
%  AvOk = avok_create;
%  AvOk = avok_create(AvOk);
%
% In/Out-put:
%  AvOk - Alis-view-Overview-keograms struct.
% 
% Call with no input argument first time.


% Data scrolling uicontrols
nr_rows = 3;
nr_data_scrolls = 9;
x_scroll = linspace(0,1,nr_data_scrolls+1);
uic_posD(1:nr_data_scrolls,1) = x_scroll(1:nr_data_scrolls)';
uic_posD(1:nr_data_scrolls,3) = diff(x_scroll)';
uic_posD(1:nr_data_scrolls,4) = 1/nr_rows;
uic_posD(1:nr_data_scrolls,2) = 1-1/nr_rows;

% Data export uicontrols
data_exports = {' 2->WS ','filenames',' t_obs ',...
                ' l_0 ','optpar',' Keo '};
nr_data_exports = 1+length([data_exports{:}]);
ex_scroll = linspace(0,1,nr_data_exports);
indx1 = 1;
for i = 1:length(data_exports)
  
  indx2 = indx1 - 1 + length(data_exports{i});
  uic_posE(i,1) = ex_scroll(indx1);
  uic_posE(i,3) = diff(ex_scroll([indx1 indx2]));
  indx1 = indx2;
end
x_scale = 1/(uic_posE(i,3) + uic_posE(i,1));
uic_posE(:,[1 3]) = x_scale * uic_posE(:,[1 3]);
uic_posE(1:i,4) = 1/nr_rows;
uic_posE(1:i,2) = 1-2/nr_rows;


% Data analysis uicontrols
data_anal = {'Movie','mono|rgb|irgb|E0','mpg|avi|mat','Char-E','SSI','Tomo'};
styles = {'pushbutton','popupmenu','popupmenu','pushbutton','pushbutton','pushbutton'};
ana_clb = {'AvOk = avok_makin_movies(AvOk);','','','Char-E','ssi','tomo'};

uic_posA = zeros(6,4);
Apos = linspace(0,1+1/6,8)
uic_posA(:,1) = Apos(1:end-2)';
uic_posA(:,3) = diff(Apos(1:end-1))';
uic_posA(1:i,4) = 1/nr_rows;
uic_posA(1:i,2) = 1-3/nr_rows;



uic_pos = [uic_posD;uic_posE];

AvOk.control_fig = figure;
set(AvOk.control_fig,'position',[256 308 350 60])
set(AvOk.control_fig,'name','ADA control panel')
pixel_pos = get(AvOk.control_fig,'position');
set(AvOk.control_fig,'units','centimeters');
cm_pos = get(AvOk.control_fig,'position');
set(AvOk.control_fig,'position',[cm_pos(1:3) nr_rows])
set(AvOk.control_fig,'units','pixels');

avok = avok_playctrl(avok,uic_posD);
avok = avok_exp_data(avok,uic_posE);
avok = avok_ana_data(avok,uic_posA,styles,data_anal,ana_clb);

%%% HIDEGUIs
set(avok.uiprevday,'HandleVisibility','callback')
set(avok.uinextday,'HandleVisibility','callback')
set(avok.nextm,'HandleVisibility','callback')
set(avok.lastm,'HandleVisibility','callback')
set(avok.nexty,'HandleVisibility','callback')
set(avok.lasty,'HandleVisibility','callback')
set(avok.first,'HandleVisibility','callback')
set(avok.export,'HandleVisibility','callback')
set(avok.exportvars,'HandleVisibility','callback')
set(avok.ana(:),'HandleVisibility','callback')

avok.fig_keo = figure;
set(avok.fig_keo,'pointer','crosshair')


function avok = avok_exp_data(avok,uic_pos)
% AVOK_EXP_DATA - Create the data export button panel
%   
avok.export = uicontrol('Units','normalized',...
                        'Style','pushbutton',...
                        'Position',uic_pos(1,:),...
                        'string','2->WS',...
                        'tooltipstring','"export"/load checked variables to matlab workspace',...
                        'Callback','alis_avok_exportvars(AvOk);');

avok.exportvars(1) = uicontrol('Units','normalized',...
                               'Style','checkbox',...
                               'Position',uic_pos(2,:),...
                               'string','filenames');
avok.exportvars(2) = uicontrol('Units','normalized',...
                               'Style','checkbox',...
                               'Position',uic_pos(3,:),...
                               'string','t_obs');
avok.exportvars(3) = uicontrol('Units','normalized',...
                               'Style','checkbox',...
                               'Position',uic_pos(4,:),...
                               'string','l_0',...
                               'fontname','symbol');
avok.exportvars(4) = uicontrol('Units','normalized',...
                               'Style','checkbox',...
                               'Position',uic_pos(5,:),...
                               'string','optpar');
avok.exportvars(5) = uicontrol('Units','normalized',...
                               'Style','checkbox',...
                               'Position',uic_pos(6,:),...
                               'string','Keo');

function avok = avok_playctrl(avok,uic_pos)
% AVOK_PLAYCTRL - Make the play,pause,ff,rew uicontrols
%   
avok.first = uicontrol('Units','normalized',...
                       'Style','pushbutton',...
                       'Position',uic_pos(1,:),...
                       'string','|<-',...
                       'tooltipstring','First day of ALIS data',...
                       'Callback','AvOk = alis_view_overview_keos([1990 1 1]);');
avok.lasty = uicontrol('Units','normalized',...
                       'Style','pushbutton',...
                       'Position',uic_pos(2,:),...
                       'string','<<<',...
                       'tooltipstring','~First day of previous year',...
                       'Callback','AvOk = alis_view_overview_keos(AvOk.lastyear);');
avok.lastm = uicontrol('Units','normalized',...
                       'Style','pushbutton',...
                       'Position',uic_pos(3,:),...
                       'string','<<',...
                       'tooltipstring','~First day previous month',...
                       'Callback','AvOk = alis_view_overview_keos(AvOk.lastmonth);');
avok.uiprevday = uicontrol('Units','normalized',...
                           'Style','pushbutton',...
                           'Position',uic_pos(4,:),...
                           'string','<',...
                           'tooltipstring','Previous day with data',...
                           'Callback','AvOk = alis_view_overview_keos(-1);');
avok.uirefrday = uicontrol('Units','normalized',...
                           'Style','pushbutton',...
                           'Position',uic_pos(5,:),...
                           'string','@',...
                           'tooltipstring','Refresh plot',...
                           'Callback','AvOk = alis_view_overview_keos(AvOk.date);');
%<-------->
avok.uinextday = uicontrol('Units','normalized',...
                           'Style','pushbutton',...
                           'Position',uic_pos(6,:),...
                           'string','>',...
                           'tooltipstring','Next day with data',...
                           'Callback','AvOk = alis_view_overview_keos(1);');
avok.nextm = uicontrol('Units','normalized',...
                       'Style','pushbutton',...
                       'Position',uic_pos(7,:),...
                       'string','>>',...
                       'tooltipstring','~First day next month',...
                       'Callback','AvOk = alis_view_overview_keos(AvOk.netxmonth);');
avok.nexty = uicontrol('Units','normalized',...
                       'Style','pushbutton',...
                       'Position',uic_pos(8,:),...
                       'string','>>>',...
                       'tooltipstring','First day next year',...
                       'Callback','AvOk = alis_view_overview_keos(AvOk.netxyear);');
avok.last = uicontrol('Units','normalized',...
                       'Style','pushbutton',...
                       'Position',uic_pos(9,:),...
                       'string','->|',...
                       'tooltipstring','Latest day with data',...
                       'Callback','AvOk = alis_view_overview_keos([2067 2 14]);');



function avok = avok_ana_data(avok,uic_pos,styles,labels,callbacks,tt)
% AVOK_ANA_DATA - Create the data analysis buttons
%   
S = 'style';
L = 'string';
C = 'callback';
P = 'position';
tts = 'tooltipstring';
for i = 1:length(styles)
  
  avok.ana(i) = uicontrol('units','normalized',...
                          S,styles{i},...
                          L,labels{i},...
                          P,uic_pos(i,:),...
                          C,callbacks{i});
end
if nargin > 5
  for i = 1:length(tt)
    
    set(avok.ana(i),tts,tt{i})
    
  end
end
