Description of in_def2
in_def2
PURPOSE
IN_DEF2 - input, with default value
SYNOPSIS
function y = in_def2(question,default_value)
DESCRIPTION
 IN_DEF2 - input, with default value
 ===========================================================
 function y = in_def2(question,default_value)
 Input        question    Text displayed when asking for input.
        default_value    This value will be retrurned if
                the user enters nothing.
 Output    The value entered by the user or the default value.
 Magnus Gustafsson & Maria Ward 1993
 Improved by Peter Rydesaeter 1998
 Used with permission
============================================================
CROSS-REFERENCE INFORMATION
This function calls:
ischar ISCHAR - return true if STR is a char-array
This function is called by:
NIPR_ASC_Ramfjord NIPR_ASC_Ramfjord - make Observation struct from filename
find_optpar FIND_OPTPAR - search the optpar data-base for best OPTPAR
find_optpar2 FIND_OPTPAR2 - search the optpar data-base for best OPTPAR
guigetspec "Private" script (!) called through skymap/starcal GUI and asks
make_tomo_ops MAKE_TOMO_OPS - User interface to set some parameters for the
SOURCE CODE
function y = in_def2(question,default_value)
% IN_DEF2 - input, with default value
% ===========================================================
% function y = in_def2(question,default_value)
%
% Input        question    Text displayed when asking for input.
%        default_value    This value will be retrurned if
%                the user enters nothing.
%
% Output    The value entered by the user or the default value.
%
% Magnus Gustafsson & Maria Ward 1993
%
% Improved by Peter Rydesaeter 1998
%
% Used with permission
%============================================================
d = num2str(default_value);
if (ischar(default_value))
  t = input([question,' {',d,'}: '],'s');
else
  t = input([question,' {',d(1:length(d)),'}: ']);
end
if (isempty(t))
  y=default_value;
else
  y=t;
end