Description of find_in_cellstr
find_in_cellstr
PURPOSE
FIND_IN_CELLSTR - search for string in cellstrings
SYNOPSIS
function ind_true = find_in_cellstr(in_str,in_cellstr)
DESCRIPTION
 FIND_IN_CELLSTR - search for string in cellstrings
 Calling:
   ind_true = find_in_cellstr(in_str,in_cellstr)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
FMInSGO_ttbs FMInSGO_ttbs - Observation struct for SGO and FMI emCCD
Lyr2obs LYR_OBS - Observation struct from filename
lyr_obs2 LYR_OBS - Observation struct from filename
lyr_obs20020117 LYR_OBS20020117 - Observation struct from filename
colorbar_labeled COLORBAR_LABELED - colorbar with label for range linear or log
SOURCE CODE
function ind_true = find_in_cellstr(in_str,in_cellstr)
% FIND_IN_CELLSTR - search for string in cellstrings
%
% Calling:
%   ind_true = find_in_cellstr(in_str,in_cellstr)
ind_true = [];
j1 = 1;
for i1 = 1:length(in_cellstr),
  if ( any(findstr(in_str,in_cellstr{i1})) )
    ind_true(j1) = i1;
    j1 = j1+1;
  end
end