Description of ImageViewer
ImageViewer
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
inimg INIMG - reads and pre-process an image.
typical_pre_proc_ops TYPICAL_PRE_PROC_OPS - Typical ALIS-fits preprocessing options
imgs_smart_caxis imgs_smart_caxis - alpha-percentile setting of color-axis,
ImageViewer
ischar ISCHAR - return true if STR is a char-array
merge_structs MERGE_STRUCTS - Merge all fields of S2 into S1.
This function is called by:
ImageViewer
SUBFUNCTIONS
function obj = ImageViewer(dirname)
function resizeFcn(obj, varargin)
function fileInfoBtnCallback(obj, varargin)
function fileMetaBtnCallback(obj, varargin)
function showDirectory(obj, dirname)
function getPreviewImages(obj, varargin)
function x = getPreviewImageData(obj, filename)
function fileListBoxCallback(obj, hObj, varargin)
function previewImageClickFcn(varargin)
function chooseDirectoryCallback(obj, varargin)
function upDirectoryCallback(obj, varargin)
function resetView(obj, varargin)
function loadImage(obj, filename)
function clearImageAxes(obj)
function winBtnDownFcn(obj, hObj, varargin)
function winBtnMotionFcn(varargin)
function zoomMotionFcn(hObj, varargin)
function scrollWheelFcn(obj, varargin)
function winBtnUpFcn(obj, hObj, varargin)
function startTimer(obj)
function stopTimerFcn(obj, varargin)
function stopTimer(obj, varargin)
function [x, info,o] = readImageFileFcn(obj, filename)
function newdirname = fixLongDirName(dirname)
function helpBtnCallback(varargin)
SOURCE CODE
classdef ImageViewer < handle
%IMAGEVIEWER  Interactively pan and zoom images on the computer.
%   IMAGEVIEWER starts a GUI for opening image files and interactive
%   panning and zooming.
%
%   IMAGEVIEWER(DIRNAME) starts the GUI with DIRNAME as the initial
%   directory.
%
%   The GUI allows you to navigate through your computer and quickly view
%   image files. It also allows you to interactively explore your images by
%   panning (clicking and drag), zooming (right-click and drag), and
%   centering view (double-clicking).
%
% Copyright 2006-2012 The MathWorks, Inc.
% VERSIONS:
%   v1.0 - first version. (was pictureviewer.m)
%   v1.1 - convert to nested functions. (Nov 13, 2006)
%   v1.2 - bug fix to deal with different image types (Nov 15, 2006)
%   v1.3 - bug fix for centering, sorting of image files.
%          add resize window feature.
%          change FINDOBJ to FINDALL (Nov 16, 2006)
%   v1.4 - cosmetic changes to the GUI.
%          a better timer management. (Dec 2, 2006)
%   v1.5 - added scroll wheel zoom functionality. This only works with
%          R2007a or later. (Jan 10, 2007)
%   v1.51 - add white background under red zoom line (June 2007)
%   v2.0 - Implemented in MATLAB Classes. (Aug 2012)
% Jiro Doke
% April 2006
%
%   v2.7 - Modified the image reading part to include AIDA-tools
%          standard ALIS fits-image reading-n-preprocessing and
%          automatic histogram clipping of intensities, also
%          changed image displaying function from image to imagesc
%          (20121115 B. Gustavsson)
properties (Hidden, Access=protected)
handles
    end
    properties (Constant, Hidden, Access=protected)
    closedHandPointer = [
        NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
        NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
        NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
        NaN,NaN,NaN,NaN,2  ,2  ,NaN,2  ,2  ,NaN,2  ,2  ,NaN,NaN,NaN,NaN
        NaN,NaN,NaN,2  ,1  ,1  ,2  ,1  ,1  ,2  ,1  ,1  ,2  ,2  ,NaN,NaN
        NaN,NaN,2  ,1  ,2  ,2  ,1  ,2  ,2  ,1  ,2  ,2  ,1  ,1  ,2  ,NaN
        NaN,NaN,2  ,1  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,1  ,2  ,1  ,2
        NaN,NaN,NaN,2  ,1  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,1  ,2
        NaN,NaN,2  ,1  ,1  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,1  ,2
        NaN,2  ,1  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,1  ,2
        NaN,2  ,1  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,1  ,2
        NaN,2  ,1  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,1  ,2  ,NaN
        NaN,NaN,2  ,1  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,1  ,2  ,NaN
        NaN,NaN,NaN,2  ,1  ,2  ,2  ,2  ,2  ,2  ,2  ,2  ,1  ,2  ,NaN,NaN
        NaN,NaN,NaN,NaN,2  ,1  ,2  ,2  ,2  ,2  ,2  ,2  ,1  ,2  ,NaN,NaN
        NaN,NaN,NaN,NaN,2  ,1  ,2  ,2  ,2  ,2  ,2  ,2  ,1  ,2  ,NaN,NaN
                        ];
    zoomInOutPointer = [
        NaN,NaN,NaN,2  ,2  ,NaN,NaN,NaN,NaN,NaN,NaN,2  ,2  ,NaN,NaN,NaN
        NaN,NaN,2  ,1  ,1  ,2  ,NaN,NaN,NaN,NaN,2  ,1  ,1  ,2  ,NaN,NaN
        NaN,2  ,1  ,1  ,1  ,1  ,2  ,NaN,NaN,2  ,2  ,1  ,1  ,2  ,2  ,NaN
        2  ,1  ,1  ,1  ,1  ,1  ,1  ,2  ,2  ,1  ,1  ,1  ,1  ,1  ,1  ,2
        2  ,1  ,2  ,1  ,1  ,2  ,1  ,2  ,2  ,1  ,1  ,1  ,1  ,1  ,1  ,2
        NaN,2  ,2  ,1  ,1  ,2  ,2  ,NaN,NaN,2  ,2  ,1  ,1  ,2  ,2  ,NaN
        NaN,NaN,2  ,1  ,1  ,2  ,NaN,NaN,NaN,NaN,2  ,1  ,1  ,2  ,NaN,NaN
        NaN,NaN,NaN,2  ,2  ,NaN,NaN,NaN,NaN,NaN,NaN,2  ,2  ,NaN,NaN,NaN
        NaN,NaN,NaN,2  ,2  ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
        NaN,NaN,2  ,1  ,1  ,2  ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
        NaN,2  ,2  ,1  ,1  ,2  ,2  ,NaN,NaN,2  ,2  ,2  ,2  ,2  ,2  ,NaN
        2  ,1  ,2  ,1  ,1  ,2  ,1  ,2  ,2  ,1  ,1  ,1  ,1  ,1  ,1  ,2
        2  ,1  ,1  ,1  ,1  ,1  ,1  ,2  ,2  ,1  ,1  ,1  ,1  ,1  ,1  ,2
        NaN,2  ,1  ,1  ,1  ,1  ,2  ,NaN,NaN,2  ,2  ,2  ,2  ,2  ,2  ,NaN
        NaN,NaN,2  ,1  ,1  ,2  ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
        NaN,NaN,NaN,2  ,2  ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
                       ];
    end
    methods
function obj = ImageViewer(dirname)
verNumber = '2.0';
if nargin == 0
  dirname = pwd;
else
  if ~ischar(dirname) || ~isdir(dirname)
    error('Invalid input argument.\n  Syntax: %s(DIRNAME)', upper(mfilename));
  end
end
delete(findall(0, 'type', 'figure', 'tag', 'ImageViewer'));
bgcolor1 = [.8 .8 .8];
txtcolor = [.3 .3 .3];
figH = figure(...
    'units'                         , 'normalized', ...
    'busyaction'                    , 'queue', ...
    'color'                         , bgcolor1, ...
    'deletefcn'                     , @obj.stopTimerFcn, ...
    'doublebuffer'                  , 'on', ...
    'handlevisibility'              , 'callback', ...
    'interruptible'                 , 'on', ...
    'menubar'                       , 'none', ...
    'name'                          , upper(mfilename), ...
    'numbertitle'                   , 'off', ...
    'outerposition'                 , [.1 .1 .8 .8], ...
    'resize'                        , 'on', ...
    'resizefcn'                     , @obj.resizeFcn, ...
    'tag'                           , 'ImageViewer', ...
    'toolbar'                       , 'none', ...
    'visible'                       , 'off', ...
    'defaultaxesunits'              , 'pixels', ...
    'defaulttextfontunits'          , 'pixels', ...
    'defaulttextfontname'           , 'Verdana', ...
    'defaulttextfontsize'           , 12, ...
    'defaultuicontrolunits'         , 'pixels', ...
    'defaultuicontrolfontunits'     , 'pixels', ...
    'defaultuicontrolfontsize'      , 10, ...
    'defaultuicontrolfontname'      , 'Verdana', ...
    'colormap'                      , bone(256),...
    'defaultuicontrolinterruptible' , 'off');
try
  if ~verLessThan('matlab', '7.4')
    set(figH, 'windowscrollwheelfcn', @obj.scrollWheelFcn);
  end
catch %#ok<CTCH>
      % verLessThan was introduced in v7.4
      % if there is an error, that means it is less than 7.4
end
uph(1) = uipanel(...
    'units'                     , 'pixels', ...
    'backgroundcolor'           , bgcolor1, ...
    'parent'                    , figH, ...
    'bordertype'                , 'beveledin', ...
    'tag'                       , 'versionPanel');
uicontrol(...
    'style'                     , 'text', ...
    'foregroundcolor'           , txtcolor, ...
    'backgroundcolor'           , bgcolor1, ...
    'horizontalalignment'       , 'center', ...
    'fontweight'                , 'bold', ...
    'string'                    , sprintf('Ver %s', verNumber), ...
    'parent'                    , uph(1), ...
    'tag'                       , 'versionText');
uph(2) = uipanel(...
    'units'                     , 'pixels', ...
    'backgroundcolor'           , bgcolor1, ...
    'parent'                    , figH, ...
    'bordertype'                , 'beveledin', ...
    'tag'                       , 'statusPanel');
uicontrol(...
    'style'                     , 'text', ...
    'foregroundcolor'           , txtcolor, ...
    'backgroundcolor'           , bgcolor1, ...
    'horizontalalignment'       , 'right', ...
    'fontweight'                , 'bold', ...
    'string'                    , '', ...
    'parent'                    , uph(2), ...
    'tag'                       , 'statusText');
uph(3) = uipanel(...
    'units'                     , 'pixels', ...
    'bordertype'                , 'etchedout', ...
    'fontname'                  , 'Verdana', ...
    'fontweight'                , 'bold', ...
    'title'                     , 'View', ...
    'titleposition'             , 'centertop', ...
    'backgroundcolor'           , bgcolor1, ...
    'parent'                    , figH, ...
    'tag'                       , 'frame1');
uicontrol(...
    'style'                     , 'text', ...
    'string'                    , '', ...
    'horizontalalignment'       , 'center', ...
    'fontweight'                , 'bold', ...
    'fontsize'                  , 12, ...
    'backgroundcolor'           , bgcolor1, ...
    'foregroundcolor'           , [.2, .2, .2], ...
    'parent'                    , uph(3), ...
    'tag'                       , 'ZoomCaptionText');
uicontrol(...
    'style'                     , 'pushbutton', ...
    'string'                    , 'Full', ...
    'fontweight'                , 'bold', ...
    'callback'                  , @obj.resetView, ...
    'enable'                    , 'off', ...
    'tooltipstring'             , 'View full image', ...
    'parent'                    , uph(3), ...
    'tag'                       , 'ResetViewBtn1');
uicontrol(...
    'style'                     , 'pushbutton', ...
    'string'                    , '100%', ...
    'fontweight'                , 'bold', ...
    'callback'                  , @obj.resetView, ...
    'enable'                    , 'off', ...
    'tooltipstring'             , 'View true size', ...
    'parent'                    , uph(3), ...
    'tag'                       , 'ResetViewBtn2');
uicontrol(...
    'style'                     , 'pushbutton', ...
    'string'                    , 'Help', ...
    'fontweight'                , 'bold', ...
    'callback'                  , @helpBtnCallback, ...
    'enable'                    , 'on', ...
    'parent'                    , figH, ...
    'tag'                       , 'HelpBtn');
uicontrol(...
    'style'                     , 'togglebutton', ...
    'string'                    , 'File Info', ...
    'fontweight'                , 'bold', ...
    'callback'                  , @obj.fileInfoBtnCallback, ...
    'enable'                    , 'off', ...
    'parent'                    , figH, ...
    'tag'                       , 'FileInfoBtn');
uicontrol(...
    'style'                     , 'togglebutton', ...
    'string'                    , 'File MetaData', ...
    'fontweight'                , 'bold', ...
    'callback'                  , @obj.fileMetaBtnCallback, ...
    'enable'                    , 'off', ...
    'parent'                    , figH, ...
    'tag'                       , 'FileMetaBtn');
uph(4) = uipanel(...
    'units'                     , 'pixels', ...
    'backgroundcolor'           , bgcolor1, ...
    'parent'                    , figH, ...
    'bordertype'                , 'beveledin', ...
    'tag'                       , 'CurrentDirectoryPanel');
uicontrol(...
    'style'                     , 'text', ...
    'backgroundcolor'           , bgcolor1, ...
    'horizontalalignment'       , 'left', ...
    'parent'                    , uph(4), ...
    'tag'                       , 'CurrentDirectoryEdit');
uicontrol(...
    'style'                     , 'pushbutton', ...
    'string'                    , '...', ...
    'backgroundcolor'           , bgcolor1, ...
    'callback'                  , @obj.chooseDirectoryCallback, ...
    'parent'                    , figH, ...
    'tag'                       , 'ChooseDirectoryBtn');
% Up Directory Icon
map = [0 0 0;bgcolor1;1 1 0;1 1 1];
upDirIcon = uint8([
    1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
    1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
    1 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1
    1 1 0 3 2 3 2 3 0 1 1 1 1 1 1 1
    1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
    1 0 2 3 2 3 2 3 2 3 2 3 2 3 2 0
    1 0 3 2 3 2 0 2 3 2 3 2 3 2 3 0
    1 0 2 3 2 0 0 0 2 3 2 3 2 3 2 0
    1 0 3 2 0 0 0 0 0 2 3 2 3 2 3 0
    1 0 2 3 2 3 0 3 2 3 2 3 2 3 2 0
    1 0 3 2 3 2 0 2 3 2 3 2 3 2 3 0
    1 0 2 3 2 3 0 0 0 0 0 3 2 3 2 0
    1 0 3 2 3 2 3 2 3 2 3 2 3 2 3 0
    1 0 2 3 2 3 2 3 2 3 2 3 2 3 2 0
    1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
                  ]);
rgbIcon = ind2rgb(upDirIcon, map);
uicontrol(...
    'style'                     , 'pushbutton', ...
    'cdata'                     , rgbIcon, ...
    'backgroundcolor'           , bgcolor1, ...
    'callback'                  , @obj.upDirectoryCallback, ...
    'parent'                    , figH, ...
    'tag'                       , 'UpDirectoryBtn');
uicontrol(...
    'style'                     , 'listbox', ...
    'backgroundcolor'           , 'white', ...
    'callback'                  , @obj.fileListBoxCallback, ...
    'fontname'                  , 'FixedWidth', ...
    'parent'                    , figH, ...
    'tag'                       , 'FileListBox');
uph(5) = uipanel(...
    'units'                     , 'pixels', ...
    'bordertype'                , 'etchedout', ...
    'backgroundcolor'           , bgcolor1, ...
    'fontname'                  , 'Verdana', ...
    'fontsize'                  , 10, ...
    'fontweight'                , 'bold', ...
    'title'                     , 'Preview', ...
    'titleposition'             , 'centertop', ...
    'parent'                    , figH, ...
    'tag'                       , 'PreviewImagePanel');
axes(...
    'handlevisibility'          , 'callback', ...
    'parent'                    , uph(5), ...
    'visible'                   , 'off', ...
    'tag'                       , 'PreviewImageAxes');
axes(...
    'box'                       , 'on', ...
    'xtick'                     , [], ...
    'ytick'                     , [], ...
    'handlevisibility'          , 'callback', ...
    'parent'                    , figH, ...
    'tag'                       , 'ImageAxes');
% for drawing the zoom line
axH = axes(...
    'units'                     , 'normalized', ...
    'position'                  , [0 0 1 1], ...
    'box'                       , 'on', ...
    'hittest'                   , 'off', ...
    'xlim'                      , [0 1], ...
    'xtick'                     , [], ...
    'ylim'                      , [0 1], ...
    'ytick'                     , [], ...
    'handlevisibility'          , 'callback', ...
    'visible'                   , 'off', ...
    'parent'                    , figH, ...
    'tag'                       , 'InvisibleAxes');
line(NaN, NaN, ...
     'linestyle'                 , '-', ...
     'linewidth'                 , 3, ...
     'color'                     , 'w', ...
     'parent'                    , axH, ...
     'tag'                       , 'ZoomLine');
line(NaN, NaN, ...
     'linestyle'                 , '--', ...
     'linewidth'                 , 2, ...
     'color'                     , 'r', ...
     'parent'                    , axH, ...
     'tag'                       , 'ZoomLine');
uicontrol(...
    'style'                     , 'listbox', ...
    'backgroundcolor'           , [.75, .75, 1], ...
    'fontname'                  , 'FixedWidth', ...
    'fontsize'                  , 14, ...
    'visible'                   , 'off', ...
    'enable'                    , 'inactive', ...
    'interruptible'             , 'off', ...
    'busyaction'                , 'queue', ...
    'horizontalalignment'       , 'left', ...
    'parent'                    , figH, ...
    'tag'                       , 'MessageTextBox');
obj.handles             = guihandles(figH);
obj.handles.figPos      = [];
obj.handles.axPos       = [];
obj.handles.lastDir     = dirname;
obj.handles.ImX         = [];
obj.handles.tm          = timer(...
    'name'            , 'image preview timer', ...
    'executionmode'   , 'fixedspacing', ...
    'objectvisibility', 'off', ...
    'taskstoexecute'  , inf, ...
    'period'          , 0.001, ...
    'startdelay'      , 3, ...
    'timerfcn'        , @obj.getPreviewImages);
resizeFcn(obj);
% Show initial directory
showDirectory(obj);
set(figH, 'visible', 'on');
        end
%--------------------------------------------------------------------------
% resizeFcn
%   This resizes the figure window appropriately
%--------------------------------------------------------------------------
function resizeFcn(obj, varargin)
set(obj.handles.ImageViewer, 'units', 'pixels');
figPos = get(obj.handles.ImageViewer, 'position');
% figure can't be too small or off the screen
if figPos(3) < 750 || figPos(4) < 500
  figPos(3) = max([750 figPos(3)]);
  figPos(4) = max([500 figPos(4)]);
  screenSize = get(0, 'screensize');
  if figPos(1)+figPos(3) > screenSize(3)
    figPos(1) = screenSize(3) - figPos(3) - 50;
  end
  if figPos(2)+figPos(4) > screenSize(4)
    figPos(2) = screenSize(4) - figPos(4) - 50;
  end
  set(obj.handles.ImageViewer, 'position', figPos);
end
set(obj.handles.versionPanel         , 'position', [1, 1, 100, 25]);
set(obj.handles.versionText          , 'position', [2, 2, 96, 20]);
set(obj.handles.statusPanel          , 'position', [102, 1, figPos(3)-102, 25]);
set(obj.handles.statusText           , 'position', [2, 2, figPos(3)-107, 20]);
set(obj.handles.frame1               , 'position', [figPos(3)-115, figPos(4)-55, 110, 53]);
set(obj.handles.ZoomCaptionText      , 'position', [5, 22, 100, 17]);
set(obj.handles.ResetViewBtn1        , 'position', [5, 2, 47, 20]);
set(obj.handles.ResetViewBtn2        , 'position', [55, 2, 47, 20]);
set(obj.handles.HelpBtn              , 'position', [figPos(3)-220, figPos(4)-28, 100, 20]);
set(obj.handles.FileInfoBtn          , 'position', [figPos(3)-220, figPos(4)-50, 100, 20]);
set(obj.handles.FileMetaBtn          , 'position', [figPos(3)-340, figPos(4)-50, 100, 20]);
set(obj.handles.CurrentDirectoryPanel, 'position', [20, figPos(4)-30, 215, 20]);
set(obj.handles.CurrentDirectoryEdit , 'position', [1, 1, 213, 18]);
set(obj.handles.ChooseDirectoryBtn   , 'position', [237, figPos(4)-30, 20, 20]);
set(obj.handles.UpDirectoryBtn       , 'position', [259, figPos(4)-30, 20, 20]);
set(obj.handles.FileListBox          , 'position', [20, 270, 260, figPos(4)-310]);
set(obj.handles.PreviewImagePanel    , 'position', [20, 40, 260, 220]);
set(obj.handles.PreviewImageAxes     , 'position', [5, 5, 245, 190]);
set(obj.handles.ImageAxes            , 'position', [300, 40, figPos(3)-310, figPos(4)-120]);
axPos = get(obj.handles.ImageAxes    , 'position');
textBoxDim  = [400, 200];
rightMargin = figPos(3)-(axPos(1)+axPos(3));
topMargin   = figPos(4)-(axPos(2)+axPos(4));
set(obj.handles.MessageTextBox      , 'position', [figPos(3)-rightMargin-textBoxDim(1), ...
                    figPos(4)-topMargin-textBoxDim(2), ...
                    textBoxDim]);
obj.handles.figPos = figPos;
obj.handles.axPos  = axPos;
titleStr = get(get(obj.handles.ImageAxes, 'title'), 'string');
if ~isempty(titleStr)
  % resize image as well
  loadImage(obj, titleStr);
end
        end
%--------------------------------------------------------------------------
% fileInfoBtnCallback
%   This displays the file info of the image that's displayed
%--------------------------------------------------------------------------
function fileInfoBtnCallback(obj, varargin)
hObj = varargin{1};
if get(hObj, 'value')
  % First 9 fields of IMFINFO are always the same
  fnames      = fieldnames(obj.handles.iminfo); fnames = fnames(1:9);
  vals        = struct2cell(obj.handles.iminfo); vals = vals(1:9);
  % Only show file name (not full path)
  [p, n, e]   = fileparts(vals{1}); %#ok<ASGLU>
  vals{1}     = [n e];
  sID         = cellfun('isclass', vals, 'char');
  dID         = cellfun('isclass', vals, 'double');
  fmt         = cell(2, 9);
  fmt(1, :)   = repmat({'%15s: '}, 1, 9);
  fmt(2, sID) = repmat({'%s|'}, 1, length(find(sID)));
  fmt(2, dID) = repmat({'%d|'}, 1, length(find(dID)));
  tmp         = [fnames(:),vals(:)]';
  str         = sprintf([fmt{:}], tmp{:});
  set(obj.handles.MessageTextBox, 'string', str, 'visible', 'on');
else
  set(obj.handles.MessageTextBox, 'visible', 'off');
end
        end
%--------------------------------------------------------------------------
% fileMetaBtnCallback
%   This displays the file info of the image that's displayed
%--------------------------------------------------------------------------
function fileMetaBtnCallback(obj, varargin)
hObj = varargin{1};
if ~isempty(obj.handles.MetaData)
  if get(hObj, 'value')
    o = obj.handles.MetaData;
    %keyboard
    str1  = sprintf('%18s %d-%02d-%02d %02d:%02d:%02d|','time:',o.time);
    str2  = sprintf('%18s %f, %f|','Obs location:',o.longlat);
    str3  = sprintf('%18s [%4.2f, %4.2f, %4.2f]|','Obs sys position:',o.xyz);
    str4  = sprintf('%18s %4.2f|','Azimuth:',o.az);
    str5  = sprintf('%18s %4.2f|','Zenith:',o.ze);
    str6  = sprintf('%18s %d|','Station nr:',o.station);
    str7  = sprintf('%18s %d|','Camera nr:',o.camnr);
    str8  = sprintf('%18s %f|','Exposure time:',o.exptime);
    str9  = sprintf('%18s %d|','Emission:',o.filter);
    str10 = sprintf('%18s %s|','Site:',o.site);
    Str = [str1,str2,str3,str4,str5,str6,str7,str8,str9,str10];
    set(obj.handles.MessageTextBox, 'string', Str, 'visible', 'on');
  else
    set(obj.handles.MessageTextBox, 'visible', 'off');
  end
end
        end
%--------------------------------------------------------------------------
% showDirectory
%   This function shows a list of image files in the directory
%--------------------------------------------------------------------------
function showDirectory(obj, dirname)
% Reset settings and images
stopTimer(obj);
cla(obj.handles.PreviewImageAxes);
axis(obj.handles.PreviewImageAxes, 'normal');
clearImageAxes(obj);
%----------------------------------------------------------------------
if nargin == 2
  obj.handles.lastDir = dirname;
else
  if isempty(obj.handles.lastDir)
    obj.handles.lastDir = pwd;
  end
end
set(obj.handles.CurrentDirectoryEdit, 'string', ...
                  fixLongDirName(obj.handles.lastDir), ...
                  'tooltipstring', obj.handles.lastDir);
% Get image formats
imf  = imformats;
exts = lower([imf.ext]);
exts_str = sprintf('%s|', exts{:}); exts_str(end) = '';
d = dir(obj.handles.lastDir);
filenames = sort({d(~[d.isdir]).name});
filenames_L = lower(filenames);
% Find all the image files
imagefiles_idx = regexp(filenames_L, sprintf('[^ \f\n\r\t\v.]+\\.(%s)',exts_str));
imagefiles = filenames(~cellfun(@isempty, imagefiles_idx));
dirnames = sort({d([d.isdir]).name});
dirnames(ismember(dirnames, {'.', '..'})) = '';
if isempty(imagefiles)
  obj.handles.imageID = [];
  obj.handles.imageNames = {};
  obj.handles.imagePreviews = {};
  runTimer = false;
else
  obj.handles.imageID = 1:length(imagefiles);
  obj.handles.imageNames = imagefiles;
  obj.handles.imagePreviews = cell(1,length(imagefiles));
  runTimer = true;
end
if isempty(dirnames)
  n = imagefiles;
else
  dirnames = strcat(repmat({'['}, 1, length(dirnames)), dirnames, repmat({']'}, 1, length(dirnames)));
  n = [dirnames, imagefiles];
  obj.handles.imageID = obj.handles.imageID + length(dirnames);
end
set(obj.handles.FileListBox, 'string', n, 'value', 1);
if runTimer
  startTimer(obj);
end
if ~isempty(obj.handles.imageID)
  set(obj.handles.ImageViewer, 'selectiontype', 'normal');
  set(obj.handles.FileListBox, 'value', obj.handles.imageID(1));
  fileListBoxCallback(obj);
end
        end
%--------------------------------------------------------------------------
% getPreviewImages
%   This is the TimerFcn for the preview timer object
%--------------------------------------------------------------------------
function getPreviewImages(obj, varargin)
try
  id = find(cellfun('isempty', obj.handles.imagePreviews));
  if ~isempty(id)
    set(obj.handles.statusText, 'string', ...
                      sprintf('Generating Thumbnails ... %d of %d', ...
                              length(obj.handles.imagePreviews)-length(id)+1, ...
                              length(obj.handles.imagePreviews)));
    drawnow;
    obj.handles.imagePreviews{id(1)} = ...
        getPreviewImageData(obj, ...
                            fullfile(get(obj.handles.CurrentDirectoryEdit, 'tooltipstring'), ...
                                     obj.handles.imageNames{id(1)}));
  else % All previews are generated. Stop timer
    set(obj.handles.statusText, 'string', '');
    stopTimer(obj);
  end
catch %#ok<CTCH>
end
        end
%--------------------------------------------------------------------------
% getPreviewImageData
%   This reads in image file for thumbnails
%--------------------------------------------------------------------------
function x = getPreviewImageData(obj, filename)
x = readImageFileFcn(obj, filename);
if ~isnan(x)
  sz = size(x);
  r = [200, 200] ./ sz(1:2);
  % Crude IMRESIZE (non-toolbox)
  xd = round(linspace(1,sz(1), round(sz(1) * min(r))));
  yd = round(linspace(1,sz(2), round(sz(2) * min(r))));
  x = x(xd, yd, :);
end
        end
%--------------------------------------------------------------------------
% fileListBoxCallback
%   This gets called when an entry is selected in the file list box
%--------------------------------------------------------------------------
function fileListBoxCallback(obj, hObj, varargin)
if nargin == 1
  hObj = obj.handles.FileListBox;
end
stopTimer(obj);
val = get(hObj, 'value');
str = cellstr(get(hObj, 'string'));
if ~isempty(str)
  switch get(obj.handles.ImageViewer, 'selectiontype')
   case 'normal'   % single click - show preview
    if str{val}(1) == '[' && str{val}(end) == ']'
      cla(obj.handles.PreviewImageAxes);
      axis(obj.handles.PreviewImageAxes, 'normal');
    else
      id = find(obj.handles.imageID == val);
      if isempty(obj.handles.imagePreviews{id});
        obj.handles.imagePreviews{id} = ...
            getPreviewImageData(obj, ...
                                fullfile(...
                                    get(obj.handles.CurrentDirectoryEdit, 'tooltipstring'), ...
                                    str{val}));
      end
      if ~isnan(obj.handles.imagePreviews{id})
        imagesc(obj.handles.imagePreviews{id}, ...
              'parent', obj.handles.PreviewImageAxes, ...
              'hittest', 'off');
        set(obj.handles.PreviewImagePanel, 'buttondownfcn', @previewImageClickFcn);
        if isa(obj.handles.imagePreviews{id},'double') | isa(obj.handles.imagePreviews{id},'single')
          imgs_smart_caxis(0.003,obj.handles.imagePreviews{id}(:))
        end
      else % unable to load image
        cla(obj.handles.PreviewImageAxes);
        set(obj.handles.PreviewImagePanel, 'buttondownfcn', '');
        text(0.5, 0.5, 'Can''t Load Image', ...
             'parent', obj.handles.PreviewImageAxes, ...
             'horizontalalignment', 'center', ...
             'verticalalignment', 'middle');
        set(obj.handles.PreviewImageAxes, 'xlim', [0 1], 'ylim', [0 1]);
      end
      axis(obj.handles.PreviewImageAxes, 'equal');
      set(obj.handles.PreviewImageAxes, 'visible', 'off');
    end
    startTimer(obj);
   case 'open'   % double click - open image and display
    if str{val}(1) == '[' && str{val}(end) == ']'
      dirname = get(obj.handles.CurrentDirectoryEdit, 'tooltipstring');
      newdirname = fullfile(dirname, str{val}(2:end-1));
      showDirectory(obj, newdirname)
    else
      obj.handles.ImX = [];
      loadImage(obj, fullfile(get(obj.handles.CurrentDirectoryEdit, 'tooltipstring'), str{val}));
      startTimer(obj);
    end
  end
end
%----------------------------------------------------------------------
% previewImageClickFcn
%   This loads the image when the thumbnail is double-clicked
%----------------------------------------------------------------------
function previewImageClickFcn(varargin)
switch get(obj.handles.ImageViewer, 'selectiontype')
 case 'open'   % double-click
  stopTimer(obj);
  obj.handles.ImX = [];
  loadImage(obj, fullfile(get(obj.handles.CurrentDirectoryEdit, 'tooltipstring'), str{val}));
  startTimer(obj);
end
            end
        end
%--------------------------------------------------------------------------
% chooseDirectoryCallback
%   This opens a directory selector
%--------------------------------------------------------------------------
function chooseDirectoryCallback(obj, varargin)
stopTimer(obj);
dirname = uigetdir(get(obj.handles.CurrentDirectoryEdit, 'tooltipstring'), ...
                   'Choose Directory');
if ischar(dirname)
  showDirectory(obj, dirname)
end
        end
%--------------------------------------------------------------------------
% upDirectoryCallback
%   This moves up the current directory
%--------------------------------------------------------------------------
function upDirectoryCallback(obj, varargin)
stopTimer(obj);
dirname = get(obj.handles.CurrentDirectoryEdit, 'tooltipstring');
dirname2 = fileparts(dirname);
if ~isequal(dirname, dirname2)
  showDirectory(obj, dirname2)
end
        end
%--------------------------------------------------------------------------
% resetView
%   This resets the view to "Full" or "100%" magnification
%--------------------------------------------------------------------------
function resetView(obj, varargin)
hObj = varargin{1};
stopTimer(obj);
set(obj.handles.MessageTextBox, 'visible', 'off');
set(obj.handles.FileInfoBtn, 'value', false);
set(obj.handles.FileMetaBtn, 'value', false);
switch get(hObj, 'string')
 case 'Full'
  xlimit = obj.handles.xlimFull;
  ylimit = obj.handles.ylimFull;
 case '100%'
  xlimit = obj.handles.xlim100;
  ylimit = obj.handles.ylim100;
end
xl = xlim(obj.handles.ImageAxes); xd = (xlimit - xl)/10;
yl = ylim(obj.handles.ImageAxes); yd = (ylimit - yl)/10;
% Restore only if needed
if ~(isequal(xd, [0 0]) && isequal(yd, [0 0]))
  set(obj.handles.statusText, 'string', 'Restoring View...');
  % Animate with "good" speed
  for id = [1, 4, 6.5, 7.8, 8.5, 9, 9.3, 9.6, 9.8, 10]
    set(obj.handles.ImageAxes, ...
        'xlim'                , xl + xd * id, ...
        'ylim'                , yl + yd * id, ...
        'cameraviewanglemode' , 'auto', ...
        'dataaspectratiomode' , 'auto', ...
        'plotboxaspectratio'  , obj.handles.pbar);
    set(obj.handles.ZoomCaptionText, 'string', sprintf('%d %%', ...
                                                      round(diff(obj.handles.xlim100)/diff(xl + xd * id)*100)));
    pause(0.01);
  end
  set(obj.handles.statusText, 'string', '');
end
startTimer(obj);
        end
%--------------------------------------------------------------------------
% loadImage
%   This loads the selected image and displays it
%--------------------------------------------------------------------------
function loadImage(obj, filename)
try
  if isempty(obj.handles.ImX)
    clearImageAxes(obj);
    set(obj.handles.statusText, 'string', 'Loading Image...');
    drawnow;
    [obj.handles.ImX, obj.handles.iminfo, obj.handles.MetaData] = readImageFileFcn(obj, filename);
  end
  if ~isnan(obj.handles.ImX)
    iH = imagesc(obj.handles.ImX, 'parent', obj.handles.ImageAxes);
    if isa(obj.handles.ImX,'double') | isa(obj.handles.ImX,'single')
      imgs_smart_caxis(0.003,obj.handles.ImX(:))
    end
    set(iH, 'hittest', 'off');
    axis(obj.handles.ImageAxes, 'equal');
    set(obj.handles.ImageAxes, ...
        'box'             , 'on', ...
        'xtick'           , [], ...
        'ytick'           , [], ...
        'buttondownfcn'   , @obj.winBtnDownFcn, ...
        'interruptible'   , 'off', ...
        'busyaction'      , 'queue', ...
        'handlevisibility', 'callback');
    set(obj.handles.ResetViewBtn1, 'enable', 'on');
    set(obj.handles.ResetViewBtn2, 'enable', 'on');
    set(obj.handles.FileInfoBtn  , 'enable', 'on');
    set(obj.handles.FileMetaBtn  , 'enable', 'on');
    set(get(obj.handles.ImageAxes, 'title'), ...
        'string'      , sprintf('%s', filename), ...
        'interpreter' , 'none');
    obj.handles.pbar     = get(obj.handles.ImageAxes, 'plotboxaspectratio');
    obj.handles.xlimFull = get(obj.handles.ImageAxes, 'xlim');
    obj.handles.ylimFull = get(obj.handles.ImageAxes, 'ylim');
    % If image is small, show at 100% size
    sz              = size(obj.handles.ImX);
    obj.handles.xlim100 = sz(2)/2 + [-1, 1] * obj.handles.axPos(3)/2;
    obj.handles.ylim100 = sz(1)/2 + [-1, 1] * obj.handles.axPos(4)/2;
    if all(obj.handles.axPos(3:4) > sz([2 1]))
      set(obj.handles.ImageAxes, ...
          'xlim'                , obj.handles.xlim100, ...
          'ylim'                , obj.handles.ylim100, ...
          'cameraviewanglemode' , 'auto', ...
          'dataaspectratiomode' , 'auto', ...
          'plotboxaspectratio'  , obj.handles.pbar);
      set(obj.handles.ZoomCaptionText, 'string', '100 %');
    else
      set(obj.handles.ZoomCaptionText, 'string', sprintf('%d %%', ...
                                                        round(diff(obj.handles.xlim100)/diff(obj.handles.xlimFull)*100)));
    end
  end
catch ME
  %keyboard
  errordlg({'Could not open image file', ME.message}, 'Error');
  clearImageAxes(obj);
end
set(obj.handles.statusText, 'string', '');
        end
%--------------------------------------------------------------------------
% clearImageAxes
%   This clears the image axis
%--------------------------------------------------------------------------
function clearImageAxes(obj)
cla(obj.handles.ImageAxes);
axis(obj.handles.ImageAxes, 'normal');
set(get(obj.handles.ImageAxes, 'title') , 'string'        , '');
set(obj.handles.ImageAxes               , 'buttondownfcn' , '');
set(obj.handles.ResetViewBtn1           , 'enable'        , 'off');
set(obj.handles.ResetViewBtn2           , 'enable'        , 'off');
set(obj.handles.FileInfoBtn             , 'enable'        , 'off', ...
                  'value'         , false);
set(obj.handles.FileMetaBtn             , 'enable'        , 'off', ...
                  'value'         , false);
set(obj.handles.ZoomCaptionText         , 'string'        , '');
set(obj.handles.MessageTextBox          , 'visible'       , 'off');
obj.handles.ImX = [];
        end
%--------------------------------------------------------------------------
% winBtnDownFcn
%   This is called when the mouse is clicked in one of the axes
%   NORMAL clicks will start panning mode.
%   ALT clicks will start zooming mode.
%   OPEN clicks will center the view.
%--------------------------------------------------------------------------
function winBtnDownFcn(obj, hObj, varargin)
stopTimer(obj);
set(obj.handles.MessageTextBox, 'visible', 'off');
set(obj.handles.FileInfoBtn, 'value', false);
set(obj.handles.FileMetaBtn, 'value', false);
switch get(obj.handles.ImageViewer, 'selectiontype')
 case 'normal'
  % Start panning mode
  xy = get(hObj, 'currentpoint');
  set(obj.handles.ImageViewer, ...
      'pointer'               , 'custom', ...
      'pointershapecdata'     , ImageViewer.closedHandPointer, ...
      'windowbuttonmotionfcn' , @winBtnMotionFcn);
  set(obj.handles.ImageViewer, 'windowbuttonupfcn', @obj.winBtnUpFcn);
 case 'alt'
  % Start zooming mode
  xl = get(hObj, 'xlim'); midX = mean(xl); rngXhalf = diff(xl) / 2;
  yl = get(hObj, 'ylim'); midY = mean(yl); rngYhalf = diff(yl) / 2;
  curPt  = mean(get(hObj, 'currentpoint'));curPt = curPt(1:2);
  curPt2 = (curPt-[midX, midY]) ./ [rngXhalf, rngYhalf];
  curPt  = [curPt; curPt];
  curPt2 = [-(1+curPt2).*[rngXhalf, rngYhalf];...
            (1-curPt2).*[rngXhalf, rngYhalf]];
  initPt = get(obj.handles.ImageViewer, 'currentpoint');
  set(obj.handles.statusText, 'string', 'Zooming...');
  set(obj.handles.ImageViewer, ...
      'pointer'               , 'custom', ...
      'pointershapecdata'     , ImageViewer.zoomInOutPointer, ...
      'windowbuttonmotionfcn' , @zoomMotionFcn);
  set(obj.handles.ImageViewer, 'windowbuttonupfcn', @obj.winBtnUpFcn);
 case 'open'
  % Center the view
  set(obj.handles.ImageViewer, 'windowbuttonupfcn', @obj.winBtnUpFcn);
  % Get current units
  un    = get(0, 'units');
  set(0, 'units', 'pixels');
  pt2   = get(0, 'pointerlocation');
  pt    = get(hObj, 'currentpoint');
  axPos = get(hObj, 'position');
  xl = get(hObj, 'xlim'); midX = mean(xl);
  yl = get(hObj, 'ylim'); midY = mean(yl);
  % update figure position in case it was moved
  obj.handles.figPos = get(obj.handles.ImageViewer, 'position');
  % get distance between cursor and center of axes
  d = norm(pt2 - (obj.handles.figPos(1:2) + axPos(1:2) + axPos(3:4)/2));
  if d > 2  % center only if distance is at least 2 pixels away
    ld = (mean(pt(:, 1:2)) - [midX, midY]) / 10;
    pd = ((obj.handles.figPos(1:2) + axPos(1:2) + axPos(3:4) / 2) - pt2) / 10;
    set(obj.handles.statusText, 'string', 'Centering...');
    % Animate with "good" speed
    for id = [1, 4, 6.5, 7.8, 8.5, 9, 9.3, 9.6, 9.8, 10]
      % Set axes limits and automatically set ticks
      % Set aspect ratios
      set(hObj, ...
          'xlim'                , xl + id * ld(1), ...
          'ylim'                , yl + id * ld(2), ...
          'cameraviewanglemode' , 'auto', ...
          'dataaspectratiomode' , 'auto', ...
          'plotboxaspectratio'  , obj.handles.pbar);
      % Move pointer with limits
      set(0, 'pointerlocation', pt2 + id * pd);
      pause(0.01);
    end
  end
  % Reset UNITS
1000   set(0, 'units', un);
1001
1002 end
1003
1004 %----------------------------------------------------------------------
1005 % winBtnMotionFcn (nested under winBtnDownFcn)
1006 %   This function is called when click-n-drag (panning) is happening
1007 %----------------------------------------------------------------------
1008 function winBtnMotionFcn(varargin)
1009
1010 pt = get(obj.handles.ImageAxes, 'currentpoint');
1011
1012 % Update axes limits and automatically set ticks
1013 % Set aspect ratios
1014 set(obj.handles.ImageAxes, ...
1015     'xlim', get(obj.handles.ImageAxes, 'xlim') + (xy(1,1)-(pt(1,1)+pt(2,1))/2), ...
1016     'ylim', get(obj.handles.ImageAxes, 'ylim') + (xy(1,2)-(pt(1,2)+pt(2,2))/2), ...
1017     'cameraviewanglemode' , 'auto', ...
1018                     'dataaspectratiomode' , 'auto', ...
1019     'plotboxaspectratio'  , obj.handles.pbar);
1020 set(obj.handles.statusText, 'string', 'Panning...');
1021
1022             end
1023
1024
1025 %----------------------------------------------------------------------
1026 % zoomMotionFcn (nested under winBtnDownFcn)
1027 %   This performs the click-n-drag zooming function. The pointer
1028 %   location relative to the initial point determines the amount of
1029 %   zoom (in or out).
1030 %----------------------------------------------------------------------
1031 function zoomMotionFcn(hObj, varargin)
1032
1033 % Power law allows for the inverse to work:
1034                 %      C^(x) * C^(-x) = 1
1035 % Choose C to get "appropriate" zoom factor
1036 C                   = 50;
1037 pt                  = get(hObj, 'currentpoint');
1038 r                   = C ^ ((initPt(2) - pt(2)) / obj.handles.figPos(4));
1039 newLimSpan          = r * curPt2; dTemp = diff(newLimSpan);
1040 pt(1)               = initPt(1);
1041
1042 % Determine new limits based on r
1043 lims                = curPt + newLimSpan;
1044
1045 % Update axes limits and automatically set ticks
1046                 % Set aspect ratios
1047 set(obj.handles.ImageAxes, ...
1048     'xlim'                , lims(:,1), ...
1049     'ylim'                , lims(:,2), ...
1050                     'cameraviewanglemode' , 'auto', ...
1051     'dataaspectratiomode' , 'auto', ...
1052     'plotboxaspectratio'  , obj.handles.pbar);
1053
1054 % Update zoom indicator line
1055 set(obj.handles.ZoomLine, ...
1056     'xdata', [initPt(1), pt(1)]/obj.handles.figPos(3), ...
1057     'ydata', [initPt(2), pt(2)]/obj.handles.figPos(4));
1058 set(obj.handles.ZoomCaptionText, 'string', sprintf('%d %%', ...
1059                                                   round(diff(obj.handles.xlim100)/dTemp(1)*100)));
1060
1061             end
1062
1063         end
1064
1065
1066 function scrollWheelFcn(obj, varargin)
1067
1068 stopTimer(obj);
1069
1070 if ~isempty(obj.handles.ImX)
1071
1072   % Power law allows for the inverse to work:
1073   %      C^(x) * C^(-x) = 1
1074   % Choose C to get "appropriate" zoom factor
1075   C                   = 1.02;
1076
1077   xl = get(obj.handles.ImageAxes, 'xlim'); midX = mean(xl); rngXhalf = diff(xl) / 2;
1078   yl = get(obj.handles.ImageAxes, 'ylim'); midY = mean(yl); rngYhalf = diff(yl) / 2;
1079   curPt  = mean(get(obj.handles.ImageAxes, 'currentpoint'));curPt = curPt(1:2);
1080   curPt2 = (curPt-[midX, midY]) ./ [rngXhalf, rngYhalf];
1081   curPt  = [curPt; curPt];
1082   curPt2 = [-(1+curPt2).*[rngXhalf, rngYhalf];...
1083             (1-curPt2).*[rngXhalf, rngYhalf]];
1084
1085   edata = varargin{2};
1086   r = C^(edata.VerticalScrollCount*edata.VerticalScrollAmount);
1087   newLimSpan          = r * curPt2;dTemp = diff(newLimSpan);
1088
1089   % Determine new limits based on r
1090   lims                = curPt + newLimSpan;
1091
1092   % Update axes limits and automatically set ticks
1093   % Set aspect ratios
1094   set(obj.handles.ImageAxes, ...
1095       'xlim'                , lims(:,1), ...
1096       'ylim'                , lims(:,2), ...
1097       'cameraviewanglemode' , 'auto', ...
1098       'dataaspectratiomode' , 'auto', ...
1099       'plotboxaspectratio'  , obj.handles.pbar);
1100
1101   % Update zoom value
1102   set(obj.handles.ZoomCaptionText, 'string', sprintf('%d %%', ...
1103                                                     round(diff(obj.handles.xlim100)/dTemp(1)*100)));
1104
1105 end
1106
1107 startTimer(obj);
1108
1109         end
1110
1111 %--------------------------------------------------------------------------
1112 % winBtnUpFcn
1113 %   This is called when the mouse is released
1114 %--------------------------------------------------------------------------
1115 function winBtnUpFcn(obj, hObj, varargin)
1116
1117 set(hObj, ...
1118     'pointer'               , 'arrow', ...
1119     'windowbuttonmotionfcn' , '');
1120 set(obj.handles.statusText, 'string', '');
1121 set(obj.handles.ZoomLine, 'xdata', NaN, 'ydata', NaN);
1122 set(obj.handles.ImageViewer, 'windowbuttonupfcn', '');
1123
1124 startTimer(obj);
1125
1126         end
1127
1128
1129 %--------------------------------------------------------------------------
1130 % startTimer
1131 %   This starts the timer. If the timer object is invalid, it creates a new
1132 %   one.
1133 %--------------------------------------------------------------------------
1134 function startTimer(obj)
1135
1136 try
1137
1138   if ~strcmpi(obj.handles.tm.Running, 'on');
1139     start(obj.handles.tm);
1140   end
1141
1142 catch %#ok<CTCH>
1143
1144   obj.handles.tm          = timer(...
1145       'name'            , 'image preview timer', ...
1146       'executionmode'   , 'fixedspacing', ...
1147       'objectvisibility', 'off', ...
1148       'taskstoexecute'  , inf, ...
1149       'period'          , 0.001, ...
1150       'startdelay'      , 3, ...
1151       'timerfcn'        , @obj.getPreviewImages);
1152   start(obj.handles.tm);
1153
1154 end
1155
1156         end
1157
1158
1159 %--------------------------------------------------------------------------
1160 % stopTimerFcn
1161 %   This gets called when the figure is closed.
1162 %--------------------------------------------------------------------------
1163 function stopTimerFcn(obj, varargin)
1164
1165 stop(obj.handles.tm);
1166 % wait until timer stops
1167 while ~strcmpi(obj.handles.tm.Running, 'off')
1168   drawnow;
1169 end
1170 delete(obj.handles.tm);
1171
1172         end
1173
1174
1175 %--------------------------------------------------------------------------
1176 % stopTimer
1177 %   This stops the timer object used for generating image previews
1178 %--------------------------------------------------------------------------
1179 function stopTimer(obj, varargin)
1180
1181 stop(obj.handles.tm);
1182
1183 % wait until timer stops
1184 while ~strcmpi(obj.handles.tm.Running, 'off')
1185   drawnow;
1186 end
1187
1188 set(obj.handles.statusText, 'string', '');
1189
1190         end
1191
1192
1193 %--------------------------------------------------------------------------
1194 % readImageFileFcn
1195 %   This function reads in the image file and converts to TRUECOLOR
1196 %--------------------------------------------------------------------------
1197 function [x, info,o] = readImageFileFcn(obj, filename)
1198
1199 try
1200
1201   info = imfinfo(filename);
1202
1203   if strcmp(info.Format,'fits')
1204     PO = typical_pre_proc_ops('alis');
1205     PO.BE = 1;
1206     % filename
1207     [x,h,o] = inimg(filename,PO);
1208
1209     info = info(1);
1210     info.Width = size(x,2);
1211     info.PrimaryData.Size = size(x);
1212     info.ColorType = 'double';
1213     info.PrimaryData = merge_structs(info.PrimaryData,o);
1214     info.MetaData = o;
1215   else
1216     o = [];
1217     [x,mp] = imread(filename);
1218   end
1219   % keyboard
1220   switch info.ColorType
1221    case 'grayscale'
1222     switch class(x)
1223      case 'logical'
1224       x = uint8(x);
1225       mp = [0 0 0;1 1 1];
1226
1227      case 'uint8'
1228       mp = gray(256);
1229
1230      case 'uint16'
1231       mp = gray(2^16);
1232
1233      case {'double','single'}
1234       cmapsz = size(get(obj.handles.ImageViewer, 'Colormap'), 1)
1235       mp = gray(cmapsz);
1236       mp = bone(256);
1237      case 'int16'
1238       x = double(x)+2^15;
1239       x = uint16((x-min(x(:)))/(max(x(:))-min(x(:)))*(2^16));
1240       mp = gray(2^16);
1241
1242      otherwise
1243       cmapsz = size(get(obj.handles.ImageViewer, 'Colormap'), 1);
1244       mp = gray(cmapsz);
1245     end
1246     x = ind2rgb(x, mp);
1247
1248    case 'indexed'
1249     if isempty(mp)
1250       mp = info.Colormap;
1251     end
1252     x = ind2rgb(x, mp);
1253
1254    otherwise
1255   end
1256
1257 catch %#ok<CTCH>
1258   x = NaN;
1259   info = [];
1260
1261 end
1262         end
1263
1264     end
1265 end
1266
1267
1268
1269 %--------------------------------------------------------------------------
1270 % fixLongDirName
1271 %   This truncates the directory string if it is too long to display
1272 %--------------------------------------------------------------------------
1273 function newdirname = fixLongDirName(dirname)
1274 % Modify string for long directory names
1275 if length(dirname) > 20
1276   [tmp1, tmp2] = strtok(dirname, filesep); %#ok<ASGLU>
1277   if isempty(tmp2)
1278     newdirname = dirname;
1279
1280   else
1281     % in case the directory name starts with a file separator.
1282     id = strfind(dirname, tmp2);
1283     tmp1 = dirname(1:id(1));
1284     [p, tmp2] = fileparts(dirname);
1285     if strcmp(tmp1, p) || isempty(tmp2)
1286       newdirname = dirname;
1287
1288     else
1289       newdirname = fullfile(tmp1, '...', tmp2);
1290       tmp3 = '';
1291       while length(newdirname) < 20
1292         tmp3 = fullfile(tmp2, tmp3);
1293         [p, tmp2] = fileparts(p);
1294         if strcmp(tmp1, p)  % reach root directory
1295           newdirname = dirname;
1296           %break; % it will break because dirname is longer than 30 chars
1297
1298         else
1299           newdirname = fullfile(tmp1, '...', tmp2, tmp3);
1300
1301         end
1302       end
1303     end
1304   end
1305 else
1306   newdirname = dirname;
1307 end
1308
1309 end
1310
1311
1312 %--------------------------------------------------------------------------
1313 % helpBtnCallback
1314 %   This opens up a help dialog box
1315 %--------------------------------------------------------------------------
1316 function helpBtnCallback(varargin)
1317
1318 helpdlg({...
1319     'Navigate through directories using the list box on the left.', ...
1320     'Single-click to see the preview.', ...
1321     'Double-click (list box OR preview image) to open and display image.', ...
1322     '', 'Click and drag to pan the image.', ...
1323     'Right click and drag to zoom. (or scroll wheel if R2007a or later)', ...
1324     'Double-click to center view.', ...
1325     '''Full'' displays the whole image.', ...
1326     '''100%'' displays the image at the true resolution.', ...
1327     '''File Info'' displays the current image file info.'}, 'Help');
1328
1329 end