Description of medfilt2
medfilt2
PURPOSE
MEDFILT2 - 2 dimensional sliding median filter
SYNOPSIS
function outM = medfilt2(inM,fc,varagin)
DESCRIPTION
 MEDFILT2 - 2 dimensional sliding median filter
   Not really, rather an approximation with repeated use of 1-D
   sliding median filter:
   medfilt1(medfilt1(inM',filtersize2)',filtersize(2))
   Working QD-solution for people without the image processing
   toolbox. This is a fall-back routine that will be used when the
   signal processing toolbox is installed but not the image
   processing TB. When both are absent the gen_susan filter is
   used as a last ditch save attempt.
 Calling:
 outM = medfilt2(inM,fc);
 See also MEDFILT1
CROSS-REFERENCE INFORMATION
This function calls:
gen_susan gen_susan - Generalized SUSAN 2-D filtering
This function is called by:
ASK_read_v ASK_READ_V - Read ASK image #i1 from current camera in current "mega-block"
runner4FlamingRays runner4FlamingRays - Estimate electron precipitation variation with E and Y
runner4FlamingRays0 % Example script: how to estimate electron energies in flaming rays
pre_proc_img PRE_PROC_IMG - systematic image correction and preprocessing of
gen_susan gen_susan - Generalized SUSAN 2-D filtering
img_splinefilter IMG_SPLINEFILTER - spline fitting filter optimum statistical filter
img_svdfilter IMG_SVDFILTER - SVD fitting filter optimum statistical filter
imgs2timeserieses imgs2timeserieses - make time-series for selected pixels
star_int_search [idstarsok,stars_par] = star_int_search(img_in,optpar,optmode,pls
star_int_search [idstarsok,stars_par] = star_int_search(img_in,optpar,optmode,plstars,OPTS)
pixel2pixel PIXEL2PIXEL - p-2-p variation in photo responce non uniformity
star_int_model STAR_INT_MODEL - Model and plot of star
star_int_search_as STAR_INT_SEARCH identifies points in image with stars, make a parametrisation
autoidentify AUTOIDENTIFY - automatically identify all the stars of PLSTARS
autoidentify AUTOIDENTIFY - automatically identify all the stars of PLSTARS
star_enhancer STAR_ENHANCER - average background-removed images to enhance stars
star_minus_bg STAR_MINUS_BG - background reduction from star
tomo_3Dfiltering TOMO_3DFILTERING -
tomo_altmaxIscaling TOMO_ALTMAXISCALING - tomographic itterative step(s).
tomo_steps TOMO_STEPS - tomographic itterative step(s).
SOURCE CODE
function outM = medfilt2(inM,fc,varagin)
% MEDFILT2 - 2 dimensional sliding median filter
%   Not really, rather an approximation with repeated use of 1-D
%   sliding median filter:
%   medfilt1(medfilt1(inM',filtersize2)',filtersize(2))
%   Working QD-solution for people without the image processing
%   toolbox. This is a fall-back routine that will be used when the
%   signal processing toolbox is installed but not the image
%   processing TB. When both are absent the gen_susan filter is
%   used as a last ditch save attempt.
%
% Calling:
% outM = medfilt2(inM,fc);
%
% See also MEDFILT1
% Copyright Bjorn Gustavsson 20050110
%   This is free software, licensed under GNU GPL version 2 or later
if nargin==1
  fc = [3 3];
end
try
  if length(fc) > 1
    outM = medfilt1(medfilt1(inM',fc(2))',fc(1));
  else
    outM = medfilt1(medfilt1(inM',fc)',fc);
  end
catch
  % The last resort, not a 2-D median filter but similar enough
  g_opts = gen_susan;
  w = ones(fc);
  w = w/sum(w(:));
  outM = gen_susan(inM,w,g_opts);
end