Description of merge_structs
merge_structs
PURPOSE
MERGE_STRUCTS - Merge all fields of S2 into S1.
SYNOPSIS
function S_out = merge_structs(S1,S2)
DESCRIPTION
 MERGE_STRUCTS - Merge all fields of S2 into S1.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ALIS_auto_overview ALIS_AUTO_OVERVIEW - automated fits data to png image conversion
ALIS_image_sequence ALIS_IMAGE_SEQUENCE - to display an ALIS image sequence as movie
ALISstdpos_visvol ALISSTDPOS_VISVOL - Display ALIS f-o-v ontop of topographic map
ssi_fe_from_4278n6300 SSI_FE_FROM_4278N6300 - Single Station Inversion Fe(E) from 4278 and 6300
ASK_add_int_radar ASK_ADD_INT_RADAR - Image intenisity inside radar beam.
ASK_fanograms ASK_FANOGRAMS - Produce keograms of a fan-beam-cut from an ASK image sequence
ASK_image_play ASK_IMAGE_PLAY - Convert image-stacks to matlab movie
ASK_image_sequence ASK_IMAGE_SEQUENCE - to display an ASK image sequence as movie, and
ASK_keogram_overlayed ASK_KEOGRAM_OVERLAYED - to plot an overlayed keogram, ASK images, and
ASK_keograms ASK_KEOGRAMS - Produce keograms keograms from an ASK image sequence
ASK_play_keolines ASK_PLAY_KEOLINES -
ASK_play_keolines2 ASK_PLAY_KEOLINES -
ASK_print_dat ASK_PRINT_DAT - prints the date corresponding to a modified
ASK_read_v ASK_READ_V - Read ASK image #i1 from current camera in current "mega-block"
ASK_slice2trmtr ASK_SLICE2TRMTR - projection matrix from blobs in slice || B to ASK-image
runner4FlamingRays runner4FlamingRays - Estimate electron precipitation variation with E and Y
gtopo2maps GTOPO2MAPS - Parse gtopo digital elevation models
getFieldLines getFieldLines - magnetic field lines from the IGRF.
img_optflow IMG_OPTFLOW - optical-flow displacements with intensity-scaling adjustment
img_splinefilter IMG_SPLINEFILTER - spline fitting filter optimum statistical filter
img_svdfilter IMG_SVDFILTER - SVD fitting filter optimum statistical filter
tomo_arcpeakfinderinslice tomo_arcpeakfinderinslice - Finds peaks of emission along [U,V]
tomo_cal tomo_cal - estimate calibration factor for fastprojection of 3D b-o-b
tomo_cal0 tomo_cal - estimate calibration factor for fastprojection of 3D b-o-b
tomo_err4sliceGACT tomo_err4sliceGACT - error function for estimating electron spectra
tomo_start_guessGACT tomo_start_guessGACT - makes 3-D distribution of volume emission rates
ImageViewer
SOURCE CODE
function S_out = merge_structs(S1,S2)
% MERGE_STRUCTS - Merge all fields of S2 into S1.
%
S_out = S1;
fields2 = fieldnames(S2);
for curr_field = [fields2(:)'],
  S_out = setfield(S_out,curr_field{:},getfield(S2,curr_field{:}));
end