Description of num8str
num8str
PURPOSE
NUM8STR - numerical to string converter
SYNOPSIS
function [s] = num8str(in)
DESCRIPTION
 NUM8STR - numerical to string converter
 NUM8STR is a higher precision version
 of the matlab function num2str.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
checkok CHECKOK - displays time and observation site GUI for user choise.
poschoice POSCHOICE - short function that updates the GUI windows
updautomat UPDAUTOMAT -
SOURCE CODE
function [s] = num8str(in)
% NUM8STR - numerical to string converter
%
% NUM8STR is a higher precision version
% of the matlab function num2str.
%       Bjorn Gustavsson
%    Copyright (c) 1997 by Bjorn Gustavsson
s = sprintf('%.8g',in);