Description of fitsfindinheader
fitsfindinheader
PURPOSE
FITSFINDINHEADER finds string S in fitsheader H
SYNOPSIS
function [j_out] = fitsfindinheader(H,s)
DESCRIPTION
 FITSFINDINHEADER finds string S in fitsheader H
 Calling:
  j = fitsfindinheader(H,s)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Kari_in_Ramfjord20011112 Kari_in_Ramfjord20011112 - make Observation struct from filename
KoschSBIG_HAARP KoschSBIG_HAARP parses an fits header for observation info
KoschSBIG_HIPAS2007 LANCS_APOGEE_FITS parses an fits header for observation info
Kosch_inSkibotn20011112 KOSCH_IN_RAMFJORD - make Observation struct from filename
lancs_apogee_fits LANCS_APOGEE_FITS parses an fits header for observation info
read_img READ_IMG - reads image data and process header info.
sbig SBIG - reads files in SBIG image format,
time_from_header TIME_FROM_HEADER parses a ALIS header for time
try_to_be_smart TRY_TO_BE_SMART parses an (ALIS) fits header for observation info
img_stack2keo imgs_stack2keo - make keograms from stack of images
imgs_keograms imgs_keograms - make keograms from sequence of image files.
SOURCE CODE
function [j_out] = fitsfindinheader(H,s)
% FITSFINDINHEADER finds string S in fitsheader H
%
% Calling:
%  j = fitsfindinheader(H,s)
% Copyright Peter Rydesaeter
j_out  = [];%if not found return empty
ji = 1;
for i1 = 1:size(H,1)
  if findstr(lower(H(i1,:)), lower(s)),
    j_out(ji) = i1;
    ji = ji+1;
  end
end