Description of fitsfindkey
fitsfindkey
PURPOSE
fitsfindkey - Searches a FITS header V for keyword S
SYNOPSIS
function [i] = fitsfindkey(V,S)
DESCRIPTION
 fitsfindkey - Searches a FITS header V for keyword S
 Calling:
  [i] = fitsfindkey(V,S)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
fits1 FITS1 reads fits files stored in LE
fits2 FITS2 reads fits files stored in BE
fits_header2infostruct FITS_HEADER2INFOSTRUCT - parse fits header, make struct of meta-data
wfits WFITS - function to write fits files.
SOURCE CODE
function [i] = fitsfindkey(V,S)
% fitsfindkey - Searches a FITS header V for keyword S
%
% Calling:
%  [i] = fitsfindkey(V,S)
for i = 1:length(V)
  if strcmp(V{i}, S),
    return;
  end
end
i=0;%if not found return 0