function OptF_struct = updautomat(SkMp)
% UPDAUTOMAT - 
%   
%      UPDAUTOMAT
%      Is the callback for the automatical opimization changes in the user interface
%      of the optplot figure. Here the changes in focal widths,
%      Azimuth, Zenith and rotation angles is made to appear on the screen.
%
% Calling: 
%   OptF_struct = updautomat(SkMp)

%   Copyright © 2011 Bjorn Gustavsson, <bjorn.gustavsson@irf.se>
%   This is free software, licensed under GNU GPL version 2 or later

sx1 = 0.01;
sx2 = 0.45;
lx1 = .43;
lx2 = .54;
ly = .085;

opt_mod = SkMp.optmod;
if opt_mod < 0
  startpar = [exp(1),(-1).^.5,pi,2^.5,0.61803,0,7,8];
  opt_mod = 7;
else
  startpar = SkMp.optpar;
  if opt_mod == 11
    opt_mod = 9;
    parStrs = {'u0','v0','f0','f1','df(u,v)','rot','azimuth','elevation'};
  else
    parStrs = {'focal(fu)','focal(fv)','Alpha','Beta','Gamma','du','dv','alfa'};
  end
end
figoptp = figure('Name','Projection par',...
                 'Position',[480,500,275,300],...
		 'Resize','off',...
		 'MenuBar','none');

ui7a(1) = uicontrol('Units','normalized',...
		   'Style','checkbox',...
		   'String',parStrs{3},...
		   'Position',[sx1,.91,lx1,ly]);
ui7a(2) = uicontrol('Units','normalized',...
		   'Style','checkbox',...
		   'String',parStrs{4},...
		   'Position',[sx1,.82,lx1,ly]);
ui7a(3) = uicontrol('Units','normalized',...
		   'Style','checkbox',...
		   'String',parStrs{5},...
		   'Position',[sx1,.73,lx1,ly]);
ui7a(4) = uicontrol('Units','normalized',...
		   'Style','checkbox',...
		   'String',parStrs{1},...
		   'Position',[sx1,.64,lx1,ly]);
ui7a(5) = uicontrol('Units','normalized',...
		   'Style','checkbox',...
		   'String',parStrs{2},...
		   'Position',[sx1,.55,lx1,ly]);
ui7a(6) = uicontrol('Units','normalized',...
		   'Style','checkbox',...
		   'String',parStrs{6},...
		   'Position',[sx1,.46,lx1,ly]);
ui7a(7) = uicontrol('Units','normalized',...
		   'Style','checkbox',...
		   'String',parStrs{7},...
		   'Position',[sx1,.37,lx1,ly]);
ui7a(12) = uicontrol('Units','normalized',...
		   'Style','checkbox',...
		   'String',parStrs{8},...
		   'Position',[sx1,.28,lx1,ly]);
ui7a(8) = uicontrol('Units','normalized',...
		   'Style','Pushbutton',...
		   'String','Mode',...
		   'Position',[sx1,.19,lx1,ly]);
ui7(1) = uicontrol('Units','normalized',...
		   'Style','Edit',...
		   'Position',[sx2,.91,lx2,ly],...
		   'String',num8str(startpar(3)));
ui7(2) = uicontrol('Units','normalized',...
		   'Style','Edit',...
		   'Position',[sx2,.82,lx2,ly],...
		   'String',num8str(startpar(4)));
ui7(3) = uicontrol('Units','normalized',...
		   'Style','Edit',...
		   'Position',[sx2,.73,lx2,ly],...
		   'String',num8str(startpar(5)));
ui7(4) = uicontrol('Units','normalized',...
		   'Style','Edit',...
		   'Position',[sx2,.64,lx2,ly],...
		   'String',num8str(startpar(1)));
ui7(5) = uicontrol('Units','normalized',...
		   'Style','Edit',...
		   'Position',[sx2,.55,lx2,ly],...
		   'String',num8str(startpar(2)));
ui7(6) = uicontrol('Units','normalized',...
		   'Style','Edit',...
		   'Position',[sx2,.46,lx2,ly],...
		   'String',num8str(startpar(6)));
ui7(7) = uicontrol('Units','normalized',...
		   'Style','Edit',...
		   'Position',[sx2,.37,lx2,ly],...
		   'String',num8str(startpar(7)));
ui7(12) = uicontrol('Units','normalized',...
		   'Style','Edit',...
		   'Position',[sx2,.28,lx2,ly],...
		   'String',num8str(startpar(8)));
ui7(8) = uicontrol('Units','normalized',...
		   'Style','Popup',...
		   'String','f tg(theta)|f sin(a theta)|f(1-a)tg(theta)+f a theta|f theta|f tg(a theta)|allsSkib|Non-param|rot-Non-par|ASK',...
		   'Position',[sx2,.19,lx2,ly],...
		   'Value',opt_mod);
ui7(10) = uicontrol('Units','normalized',...
		   'Style','Pushbutton',...
		   'String','Search',...
		   'Position',[sx1,.10,lx2+lx1+.02,ly],...
		   'Value',2,...
		   'Callback','[optpar,SkMp]=runopticsoptimization(SkMp,OptF_struct);');
ui7(11) = uicontrol('Units','normalized',...
		   'Style','Pushbutton',...
		   'String','Help',...
		   'Position',[sx1,.01,lx2+lx1+.02,ly],...
		   'Value',2,...
		   'Callback','starhelp(7)');

verstr = version;
version_nr = str2num(verstr(1:3));

if ( version_nr > 5.1 )
  
  set(ui7a(1),'TooltipString','(un)Lock the EAST-WEST angle');
  set(ui7a(2),'TooltipString','(un)Lock the NORTH-SOUTH angle');
  set(ui7a(3),'TooltipString','(un)Lock the ROLL angle');
  set(ui7a(4),'TooltipString','(un)Lock the HORIZONTAL FOCAL WIDTH');
  set(ui7a(5),'TooltipString','(un)Lock the VERTICAL FOCAL WIDTH');
  set(ui7a(6),'TooltipString','(un)Lock the horizontal displacement of optical axis');
  set(ui7a(7),'TooltipString','(un)Lock the vertical displacement of optical axis');
  set(ui7a(12),'TooltipString','(un)Lock the weighting factor alfa (relevant for mode 3)');
  set(ui7a(8),'TooltipString','Change the optical camera model, see help');
  set(ui7(1),'TooltipString','Change the EAST-WEST angle')
  set(ui7(2),'TooltipString','Change the NORTH-SOUTH angle');
  set(ui7(3),'TooltipString','Change the ROLL angle');
  set(ui7(4),'TooltipString','Change the HORIZONTAL FOCAL WIDTH');
  set(ui7(5),'TooltipString','Change the VERTICAL FOCAL WIDTH');
  set(ui7(6),'TooltipString','Change the horizontal displacement of optical axis');
  set(ui7(7),'TooltipString','Change the vertical displacement of optical axis');
  set(ui7(12),'TooltipString','Change the weighting factor alfa (relevant for mode 3)');
  set(ui7(8),'TooltipString','Change the optical camera model, see help');
  set(ui7(10),'TooltipString','Optimize the optical parameters to minimal error');
  set(ui7(11),'TooltipString','Guess what?');
  
end


OptF_struct.figopt = figoptp;
OptF_struct.ui7 = ui7;
OptF_struct.ui7a = ui7a;
SkMp.ui7 = ui7;
set(SkMp.ui7(8),'callback','SkMp = updchange_optmod(SkMp,OptF_struct);')
