Description of ASK_time_v
ASK_time_v
PURPOSE
ASK_TIME_V - returns time since the start of the sequence
SYNOPSIS
function t = ASK_time_v(i1,fullMJS)
DESCRIPTION
 ASK_TIME_V - returns time since the start of the sequence
  keyword full forces the time to be mjs, rather than seconds from the start
 Calling:
   t = ASK_time_v(i1,fullMJS)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ASK_image_sequence IMAGE_SWQUENCE - to display an ASK image sequence as movie, and
ASK_indx2datevec ASK_INDX2DATEVEC - Convert a frame index into a [yyyy,mm,dd,HH,MM,SS.FFF]
ASK_keogram_overlayed ASK_KEOGRAM_OVERLAYED - to plot an overlayed keogram, ASK images, and
ASK_line_int ASK_LINE_INT - make intensity line plots from an image sequence.
ASK_time2indx ASK_TIME2INDX - returns the imasge index for a time-vector
SOURCE CODE
function t = ASK_time_v(i1,fullMJS)
% ASK_TIME_V - returns time since the start of the sequence
%
%  keyword full forces the time to be mjs, rather than seconds from the start
%
% Calling:
%   t = ASK_time_v(i1,fullMJS)
% common vs
global vs
t = vs.vres(vs.vsel) *(i1 - vs.vnf(vs.vsel));
if nargin == 2 && fullMJS
  t = vs.vmjs(vs.vsel)+1.0*t;
end