Description of ASK_indx2datevec
ASK_indx2datevec
PURPOSE
ASK_INDX2DATEVEC - Convert a frame index into a [yyyy,mm,dd,HH,MM,SS.FFF]
SYNOPSIS
function time_V = ASK_indx2datevec(indx)
DESCRIPTION
 ASK_INDX2DATEVEC - Convert a frame index into a [yyyy,mm,dd,HH,MM,SS.FFF]
   array.
 Calling:
  time_v = ASK_indx2datevec(indx)
 Input:
  INDX - Frame index
 Output:
  TIME_V - [yyyy, mm, dd, HH, MM, SS.fff] array with date and time
           corresponding to the frame index INJDX
CROSS-REFERENCE INFORMATION
This function calls:
ASK_dat2str DAT2STR - convert a modified Julian second (mjs) to date string
ASK_time_v ASK_TIME_V - returns time since the start of the sequence
This function is called by:
ASK_keogram_overlayed ASK_KEOGRAM_OVERLAYED - to plot an overlayed keogram, ASK images, and
ASK_keograms ASK_KEOGRAMS - Produce keograms keograms from an ASK image sequence
SOURCE CODE
function time_V = ASK_indx2datevec(indx)
% ASK_INDX2DATEVEC - Convert a frame index into a [yyyy,mm,dd,HH,MM,SS.FFF]
%   array.
%
% Calling:
%  time_v = ASK_indx2datevec(indx)
% Input:
%  INDX - Frame index
% Output:
%  TIME_V - [yyyy, mm, dd, HH, MM, SS.fff] array with date and time
%           corresponding to the frame index INJDX
time_V = str2num(ASK_dat2str(ASK_time_v(indx,1),'yyyy mm dd HH MM SS.FFF'));